// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hkorpo/book/internal/primitive"
	"hkorpo/book/pkg/ent/book"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BookCreate is the builder for creating a Book entity.
type BookCreate struct {
	config
	mutation *BookMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *BookCreate) SetCreatedAt(v time.Time) *BookCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BookCreate) SetNillableCreatedAt(v *time.Time) *BookCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BookCreate) SetUpdatedAt(v time.Time) *BookCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BookCreate) SetNillableUpdatedAt(v *time.Time) *BookCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetKey sets the "key" field.
func (_c *BookCreate) SetKey(v string) *BookCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *BookCreate) SetTitle(v string) *BookCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetAuthorNames sets the "author_names" field.
func (_c *BookCreate) SetAuthorNames(v []string) *BookCreate {
	_c.mutation.SetAuthorNames(v)
	return _c
}

// SetAuthorKeys sets the "author_keys" field.
func (_c *BookCreate) SetAuthorKeys(v []string) *BookCreate {
	_c.mutation.SetAuthorKeys(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *BookCreate) SetDescription(v string) *BookCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *BookCreate) SetNillableDescription(v *string) *BookCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCoverURL sets the "cover_url" field.
func (_c *BookCreate) SetCoverURL(v string) *BookCreate {
	_c.mutation.SetCoverURL(v)
	return _c
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_c *BookCreate) SetNillableCoverURL(v *string) *BookCreate {
	if v != nil {
		_c.SetCoverURL(*v)
	}
	return _c
}

// SetUploaded sets the "uploaded" field.
func (_c *BookCreate) SetUploaded(v bool) *BookCreate {
	_c.mutation.SetUploaded(v)
	return _c
}

// SetNillableUploaded sets the "uploaded" field if the given value is not nil.
func (_c *BookCreate) SetNillableUploaded(v *bool) *BookCreate {
	if v != nil {
		_c.SetUploaded(*v)
	}
	return _c
}

// SetParsed sets the "parsed" field.
func (_c *BookCreate) SetParsed(v bool) *BookCreate {
	_c.mutation.SetParsed(v)
	return _c
}

// SetNillableParsed sets the "parsed" field if the given value is not nil.
func (_c *BookCreate) SetNillableParsed(v *bool) *BookCreate {
	if v != nil {
		_c.SetParsed(*v)
	}
	return _c
}

// SetPrepared sets the "prepared" field.
func (_c *BookCreate) SetPrepared(v bool) *BookCreate {
	_c.mutation.SetPrepared(v)
	return _c
}

// SetNillablePrepared sets the "prepared" field if the given value is not nil.
func (_c *BookCreate) SetNillablePrepared(v *bool) *BookCreate {
	if v != nil {
		_c.SetPrepared(*v)
	}
	return _c
}

// SetScriptGenerated sets the "script_generated" field.
func (_c *BookCreate) SetScriptGenerated(v bool) *BookCreate {
	_c.mutation.SetScriptGenerated(v)
	return _c
}

// SetNillableScriptGenerated sets the "script_generated" field if the given value is not nil.
func (_c *BookCreate) SetNillableScriptGenerated(v *bool) *BookCreate {
	if v != nil {
		_c.SetScriptGenerated(*v)
	}
	return _c
}

// SetTtsGenerated sets the "tts_generated" field.
func (_c *BookCreate) SetTtsGenerated(v bool) *BookCreate {
	_c.mutation.SetTtsGenerated(v)
	return _c
}

// SetNillableTtsGenerated sets the "tts_generated" field if the given value is not nil.
func (_c *BookCreate) SetNillableTtsGenerated(v *bool) *BookCreate {
	if v != nil {
		_c.SetTtsGenerated(*v)
	}
	return _c
}

// SetLanguage sets the "language" field.
func (_c *BookCreate) SetLanguage(v primitive.Language) *BookCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *BookCreate) SetNillableLanguage(v *primitive.Language) *BookCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetFailed sets the "failed" field.
func (_c *BookCreate) SetFailed(v bool) *BookCreate {
	_c.mutation.SetFailed(v)
	return _c
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_c *BookCreate) SetNillableFailed(v *bool) *BookCreate {
	if v != nil {
		_c.SetFailed(*v)
	}
	return _c
}

// SetFailedStage sets the "failed_stage" field.
func (_c *BookCreate) SetFailedStage(v string) *BookCreate {
	_c.mutation.SetFailedStage(v)
	return _c
}

// SetNillableFailedStage sets the "failed_stage" field if the given value is not nil.
func (_c *BookCreate) SetNillableFailedStage(v *string) *BookCreate {
	if v != nil {
		_c.SetFailedStage(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *BookCreate) SetErrorMessage(v string) *BookCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *BookCreate) SetNillableErrorMessage(v *string) *BookCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetRetryDisabled sets the "retry_disabled" field.
func (_c *BookCreate) SetRetryDisabled(v bool) *BookCreate {
	_c.mutation.SetRetryDisabled(v)
	return _c
}

// SetNillableRetryDisabled sets the "retry_disabled" field if the given value is not nil.
func (_c *BookCreate) SetNillableRetryDisabled(v *bool) *BookCreate {
	if v != nil {
		_c.SetRetryDisabled(*v)
	}
	return _c
}

// SetTokenUsage sets the "token_usage" field.
func (_c *BookCreate) SetTokenUsage(v primitive.TokenUsage) *BookCreate {
	_c.mutation.SetTokenUsage(v)
	return _c
}

// SetID sets the "id" field.
func (_c *BookCreate) SetID(v uuid.UUID) *BookCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BookCreate) SetNillableID(v *uuid.UUID) *BookCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the BookMutation object of the builder.
func (_c *BookCreate) Mutation() *BookMutation {
	return _c.mutation
}

// Save creates the Book in the database.
func (_c *BookCreate) Save(ctx context.Context) (*Book, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BookCreate) SaveX(ctx context.Context) *Book {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BookCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BookCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BookCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := book.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := book.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Uploaded(); !ok {
		v := book.DefaultUploaded
		_c.mutation.SetUploaded(v)
	}
	if _, ok := _c.mutation.Parsed(); !ok {
		v := book.DefaultParsed
		_c.mutation.SetParsed(v)
	}
	if _, ok := _c.mutation.Prepared(); !ok {
		v := book.DefaultPrepared
		_c.mutation.SetPrepared(v)
	}
	if _, ok := _c.mutation.ScriptGenerated(); !ok {
		v := book.DefaultScriptGenerated
		_c.mutation.SetScriptGenerated(v)
	}
	if _, ok := _c.mutation.TtsGenerated(); !ok {
		v := book.DefaultTtsGenerated
		_c.mutation.SetTtsGenerated(v)
	}
	if _, ok := _c.mutation.Language(); !ok {
		v := book.DefaultLanguage
		_c.mutation.SetLanguage(v)
	}
	if _, ok := _c.mutation.Failed(); !ok {
		v := book.DefaultFailed
		_c.mutation.SetFailed(v)
	}
	if _, ok := _c.mutation.RetryDisabled(); !ok {
		v := book.DefaultRetryDisabled
		_c.mutation.SetRetryDisabled(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := book.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BookCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Book.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Book.updated_at"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "Book.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := book.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Book.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Book.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := book.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Book.title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CoverURL(); ok {
		if err := book.CoverURLValidator(v); err != nil {
			return &ValidationError{Name: "cover_url", err: fmt.Errorf(`ent: validator failed for field "Book.cover_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Uploaded(); !ok {
		return &ValidationError{Name: "uploaded", err: errors.New(`ent: missing required field "Book.uploaded"`)}
	}
	if _, ok := _c.mutation.Parsed(); !ok {
		return &ValidationError{Name: "parsed", err: errors.New(`ent: missing required field "Book.parsed"`)}
	}
	if _, ok := _c.mutation.Prepared(); !ok {
		return &ValidationError{Name: "prepared", err: errors.New(`ent: missing required field "Book.prepared"`)}
	}
	if _, ok := _c.mutation.ScriptGenerated(); !ok {
		return &ValidationError{Name: "script_generated", err: errors.New(`ent: missing required field "Book.script_generated"`)}
	}
	if _, ok := _c.mutation.TtsGenerated(); !ok {
		return &ValidationError{Name: "tts_generated", err: errors.New(`ent: missing required field "Book.tts_generated"`)}
	}
	if _, ok := _c.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "Book.language"`)}
	}
	if v, ok := _c.mutation.Language(); ok {
		if err := book.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "Book.language": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Failed(); !ok {
		return &ValidationError{Name: "failed", err: errors.New(`ent: missing required field "Book.failed"`)}
	}
	if v, ok := _c.mutation.FailedStage(); ok {
		if err := book.FailedStageValidator(v); err != nil {
			return &ValidationError{Name: "failed_stage", err: fmt.Errorf(`ent: validator failed for field "Book.failed_stage": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RetryDisabled(); !ok {
		return &ValidationError{Name: "retry_disabled", err: errors.New(`ent: missing required field "Book.retry_disabled"`)}
	}
	return nil
}

func (_c *BookCreate) sqlSave(ctx context.Context) (*Book, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BookCreate) createSpec() (*Book, *sqlgraph.CreateSpec) {
	var (
		_node = &Book{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(book.Table, sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(book.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(book.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(book.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.AuthorNames(); ok {
		_spec.SetField(book.FieldAuthorNames, field.TypeJSON, value)
		_node.AuthorNames = value
	}
	if value, ok := _c.mutation.AuthorKeys(); ok {
		_spec.SetField(book.FieldAuthorKeys, field.TypeJSON, value)
		_node.AuthorKeys = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(book.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.CoverURL(); ok {
		_spec.SetField(book.FieldCoverURL, field.TypeString, value)
		_node.CoverURL = value
	}
	if value, ok := _c.mutation.Uploaded(); ok {
		_spec.SetField(book.FieldUploaded, field.TypeBool, value)
		_node.Uploaded = value
	}
	if value, ok := _c.mutation.Parsed(); ok {
		_spec.SetField(book.FieldParsed, field.TypeBool, value)
		_node.Parsed = value
	}
	if value, ok := _c.mutation.Prepared(); ok {
		_spec.SetField(book.FieldPrepared, field.TypeBool, value)
		_node.Prepared = value
	}
	if value, ok := _c.mutation.ScriptGenerated(); ok {
		_spec.SetField(book.FieldScriptGenerated, field.TypeBool, value)
		_node.ScriptGenerated = value
	}
	if value, ok := _c.mutation.TtsGenerated(); ok {
		_spec.SetField(book.FieldTtsGenerated, field.TypeBool, value)
		_node.TtsGenerated = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(book.FieldLanguage, field.TypeEnum, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.Failed(); ok {
		_spec.SetField(book.FieldFailed, field.TypeBool, value)
		_node.Failed = value
	}
	if value, ok := _c.mutation.FailedStage(); ok {
		_spec.SetField(book.FieldFailedStage, field.TypeString, value)
		_node.FailedStage = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(book.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.RetryDisabled(); ok {
		_spec.SetField(book.FieldRetryDisabled, field.TypeBool, value)
		_node.RetryDisabled = value
	}
	if value, ok := _c.mutation.TokenUsage(); ok {
		_spec.SetField(book.FieldTokenUsage, field.TypeJSON, value)
		_node.TokenUsage = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Book.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BookUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BookCreate) OnConflict(opts ...sql.ConflictOption) *BookUpsertOne {
	_c.conflict = opts
	return &BookUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Book.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BookCreate) OnConflictColumns(columns ...string) *BookUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BookUpsertOne{
		create: _c,
	}
}

type (
	// BookUpsertOne is the builder for "upsert"-ing
	//  one Book node.
	BookUpsertOne struct {
		create *BookCreate
	}

	// BookUpsert is the "OnConflict" setter.
	BookUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *BookUpsert) SetUpdatedAt(v time.Time) *BookUpsert {
	u.Set(book.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BookUpsert) UpdateUpdatedAt() *BookUpsert {
	u.SetExcluded(book.FieldUpdatedAt)
	return u
}

// SetKey sets the "key" field.
func (u *BookUpsert) SetKey(v string) *BookUpsert {
	u.Set(book.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *BookUpsert) UpdateKey() *BookUpsert {
	u.SetExcluded(book.FieldKey)
	return u
}

// SetTitle sets the "title" field.
func (u *BookUpsert) SetTitle(v string) *BookUpsert {
	u.Set(book.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BookUpsert) UpdateTitle() *BookUpsert {
	u.SetExcluded(book.FieldTitle)
	return u
}

// SetAuthorNames sets the "author_names" field.
func (u *BookUpsert) SetAuthorNames(v []string) *BookUpsert {
	u.Set(book.FieldAuthorNames, v)
	return u
}

// UpdateAuthorNames sets the "author_names" field to the value that was provided on create.
func (u *BookUpsert) UpdateAuthorNames() *BookUpsert {
	u.SetExcluded(book.FieldAuthorNames)
	return u
}

// ClearAuthorNames clears the value of the "author_names" field.
func (u *BookUpsert) ClearAuthorNames() *BookUpsert {
	u.SetNull(book.FieldAuthorNames)
	return u
}

// SetAuthorKeys sets the "author_keys" field.
func (u *BookUpsert) SetAuthorKeys(v []string) *BookUpsert {
	u.Set(book.FieldAuthorKeys, v)
	return u
}

// UpdateAuthorKeys sets the "author_keys" field to the value that was provided on create.
func (u *BookUpsert) UpdateAuthorKeys() *BookUpsert {
	u.SetExcluded(book.FieldAuthorKeys)
	return u
}

// ClearAuthorKeys clears the value of the "author_keys" field.
func (u *BookUpsert) ClearAuthorKeys() *BookUpsert {
	u.SetNull(book.FieldAuthorKeys)
	return u
}

// SetDescription sets the "description" field.
func (u *BookUpsert) SetDescription(v string) *BookUpsert {
	u.Set(book.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BookUpsert) UpdateDescription() *BookUpsert {
	u.SetExcluded(book.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *BookUpsert) ClearDescription() *BookUpsert {
	u.SetNull(book.FieldDescription)
	return u
}

// SetCoverURL sets the "cover_url" field.
func (u *BookUpsert) SetCoverURL(v string) *BookUpsert {
	u.Set(book.FieldCoverURL, v)
	return u
}

// UpdateCoverURL sets the "cover_url" field to the value that was provided on create.
func (u *BookUpsert) UpdateCoverURL() *BookUpsert {
	u.SetExcluded(book.FieldCoverURL)
	return u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (u *BookUpsert) ClearCoverURL() *BookUpsert {
	u.SetNull(book.FieldCoverURL)
	return u
}

// SetUploaded sets the "uploaded" field.
func (u *BookUpsert) SetUploaded(v bool) *BookUpsert {
	u.Set(book.FieldUploaded, v)
	return u
}

// UpdateUploaded sets the "uploaded" field to the value that was provided on create.
func (u *BookUpsert) UpdateUploaded() *BookUpsert {
	u.SetExcluded(book.FieldUploaded)
	return u
}

// SetParsed sets the "parsed" field.
func (u *BookUpsert) SetParsed(v bool) *BookUpsert {
	u.Set(book.FieldParsed, v)
	return u
}

// UpdateParsed sets the "parsed" field to the value that was provided on create.
func (u *BookUpsert) UpdateParsed() *BookUpsert {
	u.SetExcluded(book.FieldParsed)
	return u
}

// SetPrepared sets the "prepared" field.
func (u *BookUpsert) SetPrepared(v bool) *BookUpsert {
	u.Set(book.FieldPrepared, v)
	return u
}

// UpdatePrepared sets the "prepared" field to the value that was provided on create.
func (u *BookUpsert) UpdatePrepared() *BookUpsert {
	u.SetExcluded(book.FieldPrepared)
	return u
}

// SetScriptGenerated sets the "script_generated" field.
func (u *BookUpsert) SetScriptGenerated(v bool) *BookUpsert {
	u.Set(book.FieldScriptGenerated, v)
	return u
}

// UpdateScriptGenerated sets the "script_generated" field to the value that was provided on create.
func (u *BookUpsert) UpdateScriptGenerated() *BookUpsert {
	u.SetExcluded(book.FieldScriptGenerated)
	return u
}

// SetTtsGenerated sets the "tts_generated" field.
func (u *BookUpsert) SetTtsGenerated(v bool) *BookUpsert {
	u.Set(book.FieldTtsGenerated, v)
	return u
}

// UpdateTtsGenerated sets the "tts_generated" field to the value that was provided on create.
func (u *BookUpsert) UpdateTtsGenerated() *BookUpsert {
	u.SetExcluded(book.FieldTtsGenerated)
	return u
}

// SetLanguage sets the "language" field.
func (u *BookUpsert) SetLanguage(v primitive.Language) *BookUpsert {
	u.Set(book.FieldLanguage, v)
	return u
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *BookUpsert) UpdateLanguage() *BookUpsert {
	u.SetExcluded(book.FieldLanguage)
	return u
}

// SetFailed sets the "failed" field.
func (u *BookUpsert) SetFailed(v bool) *BookUpsert {
	u.Set(book.FieldFailed, v)
	return u
}

// UpdateFailed sets the "failed" field to the value that was provided on create.
func (u *BookUpsert) UpdateFailed() *BookUpsert {
	u.SetExcluded(book.FieldFailed)
	return u
}

// SetFailedStage sets the "failed_stage" field.
func (u *BookUpsert) SetFailedStage(v string) *BookUpsert {
	u.Set(book.FieldFailedStage, v)
	return u
}

// UpdateFailedStage sets the "failed_stage" field to the value that was provided on create.
func (u *BookUpsert) UpdateFailedStage() *BookUpsert {
	u.SetExcluded(book.FieldFailedStage)
	return u
}

// ClearFailedStage clears the value of the "failed_stage" field.
func (u *BookUpsert) ClearFailedStage() *BookUpsert {
	u.SetNull(book.FieldFailedStage)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *BookUpsert) SetErrorMessage(v string) *BookUpsert {
	u.Set(book.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *BookUpsert) UpdateErrorMessage() *BookUpsert {
	u.SetExcluded(book.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *BookUpsert) ClearErrorMessage() *BookUpsert {
	u.SetNull(book.FieldErrorMessage)
	return u
}

// SetRetryDisabled sets the "retry_disabled" field.
func (u *BookUpsert) SetRetryDisabled(v bool) *BookUpsert {
	u.Set(book.FieldRetryDisabled, v)
	return u
}

// UpdateRetryDisabled sets the "retry_disabled" field to the value that was provided on create.
func (u *BookUpsert) UpdateRetryDisabled() *BookUpsert {
	u.SetExcluded(book.FieldRetryDisabled)
	return u
}

// SetTokenUsage sets the "token_usage" field.
func (u *BookUpsert) SetTokenUsage(v primitive.TokenUsage) *BookUpsert {
	u.Set(book.FieldTokenUsage, v)
	return u
}

// UpdateTokenUsage sets the "token_usage" field to the value that was provided on create.
func (u *BookUpsert) UpdateTokenUsage() *BookUpsert {
	u.SetExcluded(book.FieldTokenUsage)
	return u
}

// ClearTokenUsage clears the value of the "token_usage" field.
func (u *BookUpsert) ClearTokenUsage() *BookUpsert {
	u.SetNull(book.FieldTokenUsage)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Book.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(book.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BookUpsertOne) UpdateNewValues() *BookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(book.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(book.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Book.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BookUpsertOne) Ignore() *BookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BookUpsertOne) DoNothing() *BookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BookCreate.OnConflict
// documentation for more info.
func (u *BookUpsertOne) Update(set func(*BookUpsert)) *BookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BookUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BookUpsertOne) SetUpdatedAt(v time.Time) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateUpdatedAt() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetKey sets the "key" field.
func (u *BookUpsertOne) SetKey(v string) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateKey() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateKey()
	})
}

// SetTitle sets the "title" field.
func (u *BookUpsertOne) SetTitle(v string) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateTitle() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateTitle()
	})
}

// SetAuthorNames sets the "author_names" field.
func (u *BookUpsertOne) SetAuthorNames(v []string) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetAuthorNames(v)
	})
}

// UpdateAuthorNames sets the "author_names" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateAuthorNames() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateAuthorNames()
	})
}

// ClearAuthorNames clears the value of the "author_names" field.
func (u *BookUpsertOne) ClearAuthorNames() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.ClearAuthorNames()
	})
}

// SetAuthorKeys sets the "author_keys" field.
func (u *BookUpsertOne) SetAuthorKeys(v []string) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetAuthorKeys(v)
	})
}

// UpdateAuthorKeys sets the "author_keys" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateAuthorKeys() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateAuthorKeys()
	})
}

// ClearAuthorKeys clears the value of the "author_keys" field.
func (u *BookUpsertOne) ClearAuthorKeys() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.ClearAuthorKeys()
	})
}

// SetDescription sets the "description" field.
func (u *BookUpsertOne) SetDescription(v string) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateDescription() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *BookUpsertOne) ClearDescription() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.ClearDescription()
	})
}

// SetCoverURL sets the "cover_url" field.
func (u *BookUpsertOne) SetCoverURL(v string) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetCoverURL(v)
	})
}

// UpdateCoverURL sets the "cover_url" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateCoverURL() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateCoverURL()
	})
}

// ClearCoverURL clears the value of the "cover_url" field.
func (u *BookUpsertOne) ClearCoverURL() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.ClearCoverURL()
	})
}

// SetUploaded sets the "uploaded" field.
func (u *BookUpsertOne) SetUploaded(v bool) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetUploaded(v)
	})
}

// UpdateUploaded sets the "uploaded" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateUploaded() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateUploaded()
	})
}

// SetParsed sets the "parsed" field.
func (u *BookUpsertOne) SetParsed(v bool) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetParsed(v)
	})
}

// UpdateParsed sets the "parsed" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateParsed() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateParsed()
	})
}

// SetPrepared sets the "prepared" field.
func (u *BookUpsertOne) SetPrepared(v bool) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetPrepared(v)
	})
}

// UpdatePrepared sets the "prepared" field to the value that was provided on create.
func (u *BookUpsertOne) UpdatePrepared() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdatePrepared()
	})
}

// SetScriptGenerated sets the "script_generated" field.
func (u *BookUpsertOne) SetScriptGenerated(v bool) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetScriptGenerated(v)
	})
}

// UpdateScriptGenerated sets the "script_generated" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateScriptGenerated() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateScriptGenerated()
	})
}

// SetTtsGenerated sets the "tts_generated" field.
func (u *BookUpsertOne) SetTtsGenerated(v bool) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetTtsGenerated(v)
	})
}

// UpdateTtsGenerated sets the "tts_generated" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateTtsGenerated() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateTtsGenerated()
	})
}

// SetLanguage sets the "language" field.
func (u *BookUpsertOne) SetLanguage(v primitive.Language) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetLanguage(v)
	})
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateLanguage() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateLanguage()
	})
}

// SetFailed sets the "failed" field.
func (u *BookUpsertOne) SetFailed(v bool) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetFailed(v)
	})
}

// UpdateFailed sets the "failed" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateFailed() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateFailed()
	})
}

// SetFailedStage sets the "failed_stage" field.
func (u *BookUpsertOne) SetFailedStage(v string) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetFailedStage(v)
	})
}

// UpdateFailedStage sets the "failed_stage" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateFailedStage() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateFailedStage()
	})
}

// ClearFailedStage clears the value of the "failed_stage" field.
func (u *BookUpsertOne) ClearFailedStage() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.ClearFailedStage()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *BookUpsertOne) SetErrorMessage(v string) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateErrorMessage() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *BookUpsertOne) ClearErrorMessage() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.ClearErrorMessage()
	})
}

// SetRetryDisabled sets the "retry_disabled" field.
func (u *BookUpsertOne) SetRetryDisabled(v bool) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetRetryDisabled(v)
	})
}

// UpdateRetryDisabled sets the "retry_disabled" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateRetryDisabled() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateRetryDisabled()
	})
}

// SetTokenUsage sets the "token_usage" field.
func (u *BookUpsertOne) SetTokenUsage(v primitive.TokenUsage) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetTokenUsage(v)
	})
}

// UpdateTokenUsage sets the "token_usage" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateTokenUsage() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateTokenUsage()
	})
}

// ClearTokenUsage clears the value of the "token_usage" field.
func (u *BookUpsertOne) ClearTokenUsage() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.ClearTokenUsage()
	})
}

// Exec executes the query.
func (u *BookUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BookCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BookUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BookUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: BookUpsertOne.ID is not supported by MySQL driver. Use BookUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BookUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BookCreateBulk is the builder for creating many Book entities in bulk.
type BookCreateBulk struct {
	config
	err      error
	builders []*BookCreate
	conflict []sql.ConflictOption
}

// Save creates the Book entities in the database.
func (_c *BookCreateBulk) Save(ctx context.Context) ([]*Book, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Book, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BookMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BookCreateBulk) SaveX(ctx context.Context) []*Book {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BookCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BookCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Book.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BookUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *BookCreateBulk) OnConflict(opts ...sql.ConflictOption) *BookUpsertBulk {
	_c.conflict = opts
	return &BookUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Book.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BookCreateBulk) OnConflictColumns(columns ...string) *BookUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BookUpsertBulk{
		create: _c,
	}
}

// BookUpsertBulk is the builder for "upsert"-ing
// a bulk of Book nodes.
type BookUpsertBulk struct {
	create *BookCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Book.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(book.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BookUpsertBulk) UpdateNewValues() *BookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(book.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(book.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Book.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BookUpsertBulk) Ignore() *BookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BookUpsertBulk) DoNothing() *BookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BookCreateBulk.OnConflict
// documentation for more info.
func (u *BookUpsertBulk) Update(set func(*BookUpsert)) *BookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BookUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BookUpsertBulk) SetUpdatedAt(v time.Time) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateUpdatedAt() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetKey sets the "key" field.
func (u *BookUpsertBulk) SetKey(v string) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateKey() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateKey()
	})
}

// SetTitle sets the "title" field.
func (u *BookUpsertBulk) SetTitle(v string) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateTitle() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateTitle()
	})
}

// SetAuthorNames sets the "author_names" field.
func (u *BookUpsertBulk) SetAuthorNames(v []string) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetAuthorNames(v)
	})
}

// UpdateAuthorNames sets the "author_names" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateAuthorNames() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateAuthorNames()
	})
}

// ClearAuthorNames clears the value of the "author_names" field.
func (u *BookUpsertBulk) ClearAuthorNames() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.ClearAuthorNames()
	})
}

// SetAuthorKeys sets the "author_keys" field.
func (u *BookUpsertBulk) SetAuthorKeys(v []string) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetAuthorKeys(v)
	})
}

// UpdateAuthorKeys sets the "author_keys" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateAuthorKeys() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateAuthorKeys()
	})
}

// ClearAuthorKeys clears the value of the "author_keys" field.
func (u *BookUpsertBulk) ClearAuthorKeys() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.ClearAuthorKeys()
	})
}

// SetDescription sets the "description" field.
func (u *BookUpsertBulk) SetDescription(v string) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateDescription() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *BookUpsertBulk) ClearDescription() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.ClearDescription()
	})
}

// SetCoverURL sets the "cover_url" field.
func (u *BookUpsertBulk) SetCoverURL(v string) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetCoverURL(v)
	})
}

// UpdateCoverURL sets the "cover_url" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateCoverURL() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateCoverURL()
	})
}

// ClearCoverURL clears the value of the "cover_url" field.
func (u *BookUpsertBulk) ClearCoverURL() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.ClearCoverURL()
	})
}

// SetUploaded sets the "uploaded" field.
func (u *BookUpsertBulk) SetUploaded(v bool) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetUploaded(v)
	})
}

// UpdateUploaded sets the "uploaded" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateUploaded() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateUploaded()
	})
}

// SetParsed sets the "parsed" field.
func (u *BookUpsertBulk) SetParsed(v bool) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetParsed(v)
	})
}

// UpdateParsed sets the "parsed" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateParsed() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateParsed()
	})
}

// SetPrepared sets the "prepared" field.
func (u *BookUpsertBulk) SetPrepared(v bool) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetPrepared(v)
	})
}

// UpdatePrepared sets the "prepared" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdatePrepared() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdatePrepared()
	})
}

// SetScriptGenerated sets the "script_generated" field.
func (u *BookUpsertBulk) SetScriptGenerated(v bool) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetScriptGenerated(v)
	})
}

// UpdateScriptGenerated sets the "script_generated" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateScriptGenerated() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateScriptGenerated()
	})
}

// SetTtsGenerated sets the "tts_generated" field.
func (u *BookUpsertBulk) SetTtsGenerated(v bool) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetTtsGenerated(v)
	})
}

// UpdateTtsGenerated sets the "tts_generated" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateTtsGenerated() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateTtsGenerated()
	})
}

// SetLanguage sets the "language" field.
func (u *BookUpsertBulk) SetLanguage(v primitive.Language) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetLanguage(v)
	})
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateLanguage() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateLanguage()
	})
}

// SetFailed sets the "failed" field.
func (u *BookUpsertBulk) SetFailed(v bool) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetFailed(v)
	})
}

// UpdateFailed sets the "failed" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateFailed() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateFailed()
	})
}

// SetFailedStage sets the "failed_stage" field.
func (u *BookUpsertBulk) SetFailedStage(v string) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetFailedStage(v)
	})
}

// UpdateFailedStage sets the "failed_stage" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateFailedStage() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateFailedStage()
	})
}

// ClearFailedStage clears the value of the "failed_stage" field.
func (u *BookUpsertBulk) ClearFailedStage() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.ClearFailedStage()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *BookUpsertBulk) SetErrorMessage(v string) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateErrorMessage() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *BookUpsertBulk) ClearErrorMessage() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.ClearErrorMessage()
	})
}

// SetRetryDisabled sets the "retry_disabled" field.
func (u *BookUpsertBulk) SetRetryDisabled(v bool) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetRetryDisabled(v)
	})
}

// UpdateRetryDisabled sets the "retry_disabled" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateRetryDisabled() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateRetryDisabled()
	})
}

// SetTokenUsage sets the "token_usage" field.
func (u *BookUpsertBulk) SetTokenUsage(v primitive.TokenUsage) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetTokenUsage(v)
	})
}

// UpdateTokenUsage sets the "token_usage" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateTokenUsage() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateTokenUsage()
	})
}

// ClearTokenUsage clears the value of the "token_usage" field.
func (u *BookUpsertBulk) ClearTokenUsage() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.ClearTokenUsage()
	})
}

// Exec executes the query.
func (u *BookUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BookCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BookCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BookUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
