// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hkorpo/book/internal/primitive"
	"hkorpo/book/pkg/ent/book"
	"hkorpo/book/pkg/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// BookUpdate is the builder for updating Book entities.
type BookUpdate struct {
	config
	hooks    []Hook
	mutation *BookMutation
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdate) Where(ps ...predicate.Book) *BookUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BookUpdate) SetUpdatedAt(v time.Time) *BookUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKey sets the "key" field.
func (_u *BookUpdate) SetKey(v string) *BookUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *BookUpdate) SetNillableKey(v *string) *BookUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *BookUpdate) SetTitle(v string) *BookUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookUpdate) SetNillableTitle(v *string) *BookUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAuthorNames sets the "author_names" field.
func (_u *BookUpdate) SetAuthorNames(v []string) *BookUpdate {
	_u.mutation.SetAuthorNames(v)
	return _u
}

// AppendAuthorNames appends value to the "author_names" field.
func (_u *BookUpdate) AppendAuthorNames(v []string) *BookUpdate {
	_u.mutation.AppendAuthorNames(v)
	return _u
}

// ClearAuthorNames clears the value of the "author_names" field.
func (_u *BookUpdate) ClearAuthorNames() *BookUpdate {
	_u.mutation.ClearAuthorNames()
	return _u
}

// SetAuthorKeys sets the "author_keys" field.
func (_u *BookUpdate) SetAuthorKeys(v []string) *BookUpdate {
	_u.mutation.SetAuthorKeys(v)
	return _u
}

// AppendAuthorKeys appends value to the "author_keys" field.
func (_u *BookUpdate) AppendAuthorKeys(v []string) *BookUpdate {
	_u.mutation.AppendAuthorKeys(v)
	return _u
}

// ClearAuthorKeys clears the value of the "author_keys" field.
func (_u *BookUpdate) ClearAuthorKeys() *BookUpdate {
	_u.mutation.ClearAuthorKeys()
	return _u
}

// SetDescription sets the "description" field.
func (_u *BookUpdate) SetDescription(v string) *BookUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BookUpdate) SetNillableDescription(v *string) *BookUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *BookUpdate) ClearDescription() *BookUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *BookUpdate) SetCoverURL(v string) *BookUpdate {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *BookUpdate) SetNillableCoverURL(v *string) *BookUpdate {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (_u *BookUpdate) ClearCoverURL() *BookUpdate {
	_u.mutation.ClearCoverURL()
	return _u
}

// SetUploaded sets the "uploaded" field.
func (_u *BookUpdate) SetUploaded(v bool) *BookUpdate {
	_u.mutation.SetUploaded(v)
	return _u
}

// SetNillableUploaded sets the "uploaded" field if the given value is not nil.
func (_u *BookUpdate) SetNillableUploaded(v *bool) *BookUpdate {
	if v != nil {
		_u.SetUploaded(*v)
	}
	return _u
}

// SetParsed sets the "parsed" field.
func (_u *BookUpdate) SetParsed(v bool) *BookUpdate {
	_u.mutation.SetParsed(v)
	return _u
}

// SetNillableParsed sets the "parsed" field if the given value is not nil.
func (_u *BookUpdate) SetNillableParsed(v *bool) *BookUpdate {
	if v != nil {
		_u.SetParsed(*v)
	}
	return _u
}

// SetPrepared sets the "prepared" field.
func (_u *BookUpdate) SetPrepared(v bool) *BookUpdate {
	_u.mutation.SetPrepared(v)
	return _u
}

// SetNillablePrepared sets the "prepared" field if the given value is not nil.
func (_u *BookUpdate) SetNillablePrepared(v *bool) *BookUpdate {
	if v != nil {
		_u.SetPrepared(*v)
	}
	return _u
}

// SetScriptGenerated sets the "script_generated" field.
func (_u *BookUpdate) SetScriptGenerated(v bool) *BookUpdate {
	_u.mutation.SetScriptGenerated(v)
	return _u
}

// SetNillableScriptGenerated sets the "script_generated" field if the given value is not nil.
func (_u *BookUpdate) SetNillableScriptGenerated(v *bool) *BookUpdate {
	if v != nil {
		_u.SetScriptGenerated(*v)
	}
	return _u
}

// SetTtsGenerated sets the "tts_generated" field.
func (_u *BookUpdate) SetTtsGenerated(v bool) *BookUpdate {
	_u.mutation.SetTtsGenerated(v)
	return _u
}

// SetNillableTtsGenerated sets the "tts_generated" field if the given value is not nil.
func (_u *BookUpdate) SetNillableTtsGenerated(v *bool) *BookUpdate {
	if v != nil {
		_u.SetTtsGenerated(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *BookUpdate) SetLanguage(v primitive.Language) *BookUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *BookUpdate) SetNillableLanguage(v *primitive.Language) *BookUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetFailed sets the "failed" field.
func (_u *BookUpdate) SetFailed(v bool) *BookUpdate {
	_u.mutation.SetFailed(v)
	return _u
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_u *BookUpdate) SetNillableFailed(v *bool) *BookUpdate {
	if v != nil {
		_u.SetFailed(*v)
	}
	return _u
}

// SetFailedStage sets the "failed_stage" field.
func (_u *BookUpdate) SetFailedStage(v string) *BookUpdate {
	_u.mutation.SetFailedStage(v)
	return _u
}

// SetNillableFailedStage sets the "failed_stage" field if the given value is not nil.
func (_u *BookUpdate) SetNillableFailedStage(v *string) *BookUpdate {
	if v != nil {
		_u.SetFailedStage(*v)
	}
	return _u
}

// ClearFailedStage clears the value of the "failed_stage" field.
func (_u *BookUpdate) ClearFailedStage() *BookUpdate {
	_u.mutation.ClearFailedStage()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *BookUpdate) SetErrorMessage(v string) *BookUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *BookUpdate) SetNillableErrorMessage(v *string) *BookUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *BookUpdate) ClearErrorMessage() *BookUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetTokenUsage sets the "token_usage" field.
func (_u *BookUpdate) SetTokenUsage(v primitive.TokenUsage) *BookUpdate {
	_u.mutation.SetTokenUsage(v)
	return _u
}

// ClearTokenUsage clears the value of the "token_usage" field.
func (_u *BookUpdate) ClearTokenUsage() *BookUpdate {
	_u.mutation.ClearTokenUsage()
	return _u
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdate) Mutation() *BookMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BookUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BookUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BookUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := book.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := book.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Book.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := book.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Book.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverURL(); ok {
		if err := book.CoverURLValidator(v); err != nil {
			return &ValidationError{Name: "cover_url", err: fmt.Errorf(`ent: validator failed for field "Book.cover_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := book.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "Book.language": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailedStage(); ok {
		if err := book.FailedStageValidator(v); err != nil {
			return &ValidationError{Name: "failed_stage", err: fmt.Errorf(`ent: validator failed for field "Book.failed_stage": %w`, err)}
		}
	}
	return nil
}

func (_u *BookUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(book.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(book.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthorNames(); ok {
		_spec.SetField(book.FieldAuthorNames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAuthorNames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, book.FieldAuthorNames, value)
		})
	}
	if _u.mutation.AuthorNamesCleared() {
		_spec.ClearField(book.FieldAuthorNames, field.TypeJSON)
	}
	if value, ok := _u.mutation.AuthorKeys(); ok {
		_spec.SetField(book.FieldAuthorKeys, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAuthorKeys(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, book.FieldAuthorKeys, value)
		})
	}
	if _u.mutation.AuthorKeysCleared() {
		_spec.ClearField(book.FieldAuthorKeys, field.TypeJSON)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(book.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(book.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(book.FieldCoverURL, field.TypeString, value)
	}
	if _u.mutation.CoverURLCleared() {
		_spec.ClearField(book.FieldCoverURL, field.TypeString)
	}
	if value, ok := _u.mutation.Uploaded(); ok {
		_spec.SetField(book.FieldUploaded, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Parsed(); ok {
		_spec.SetField(book.FieldParsed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Prepared(); ok {
		_spec.SetField(book.FieldPrepared, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ScriptGenerated(); ok {
		_spec.SetField(book.FieldScriptGenerated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TtsGenerated(); ok {
		_spec.SetField(book.FieldTtsGenerated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(book.FieldLanguage, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Failed(); ok {
		_spec.SetField(book.FieldFailed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FailedStage(); ok {
		_spec.SetField(book.FieldFailedStage, field.TypeString, value)
	}
	if _u.mutation.FailedStageCleared() {
		_spec.ClearField(book.FieldFailedStage, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(book.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(book.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.TokenUsage(); ok {
		_spec.SetField(book.FieldTokenUsage, field.TypeJSON, value)
	}
	if _u.mutation.TokenUsageCleared() {
		_spec.ClearField(book.FieldTokenUsage, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BookUpdateOne is the builder for updating a single Book entity.
type BookUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BookUpdateOne) SetUpdatedAt(v time.Time) *BookUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKey sets the "key" field.
func (_u *BookUpdateOne) SetKey(v string) *BookUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableKey(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *BookUpdateOne) SetTitle(v string) *BookUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableTitle(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAuthorNames sets the "author_names" field.
func (_u *BookUpdateOne) SetAuthorNames(v []string) *BookUpdateOne {
	_u.mutation.SetAuthorNames(v)
	return _u
}

// AppendAuthorNames appends value to the "author_names" field.
func (_u *BookUpdateOne) AppendAuthorNames(v []string) *BookUpdateOne {
	_u.mutation.AppendAuthorNames(v)
	return _u
}

// ClearAuthorNames clears the value of the "author_names" field.
func (_u *BookUpdateOne) ClearAuthorNames() *BookUpdateOne {
	_u.mutation.ClearAuthorNames()
	return _u
}

// SetAuthorKeys sets the "author_keys" field.
func (_u *BookUpdateOne) SetAuthorKeys(v []string) *BookUpdateOne {
	_u.mutation.SetAuthorKeys(v)
	return _u
}

// AppendAuthorKeys appends value to the "author_keys" field.
func (_u *BookUpdateOne) AppendAuthorKeys(v []string) *BookUpdateOne {
	_u.mutation.AppendAuthorKeys(v)
	return _u
}

// ClearAuthorKeys clears the value of the "author_keys" field.
func (_u *BookUpdateOne) ClearAuthorKeys() *BookUpdateOne {
	_u.mutation.ClearAuthorKeys()
	return _u
}

// SetDescription sets the "description" field.
func (_u *BookUpdateOne) SetDescription(v string) *BookUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableDescription(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *BookUpdateOne) ClearDescription() *BookUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *BookUpdateOne) SetCoverURL(v string) *BookUpdateOne {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableCoverURL(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// ClearCoverURL clears the value of the "cover_url" field.
func (_u *BookUpdateOne) ClearCoverURL() *BookUpdateOne {
	_u.mutation.ClearCoverURL()
	return _u
}

// SetUploaded sets the "uploaded" field.
func (_u *BookUpdateOne) SetUploaded(v bool) *BookUpdateOne {
	_u.mutation.SetUploaded(v)
	return _u
}

// SetNillableUploaded sets the "uploaded" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableUploaded(v *bool) *BookUpdateOne {
	if v != nil {
		_u.SetUploaded(*v)
	}
	return _u
}

// SetParsed sets the "parsed" field.
func (_u *BookUpdateOne) SetParsed(v bool) *BookUpdateOne {
	_u.mutation.SetParsed(v)
	return _u
}

// SetNillableParsed sets the "parsed" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableParsed(v *bool) *BookUpdateOne {
	if v != nil {
		_u.SetParsed(*v)
	}
	return _u
}

// SetPrepared sets the "prepared" field.
func (_u *BookUpdateOne) SetPrepared(v bool) *BookUpdateOne {
	_u.mutation.SetPrepared(v)
	return _u
}

// SetNillablePrepared sets the "prepared" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillablePrepared(v *bool) *BookUpdateOne {
	if v != nil {
		_u.SetPrepared(*v)
	}
	return _u
}

// SetScriptGenerated sets the "script_generated" field.
func (_u *BookUpdateOne) SetScriptGenerated(v bool) *BookUpdateOne {
	_u.mutation.SetScriptGenerated(v)
	return _u
}

// SetNillableScriptGenerated sets the "script_generated" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableScriptGenerated(v *bool) *BookUpdateOne {
	if v != nil {
		_u.SetScriptGenerated(*v)
	}
	return _u
}

// SetTtsGenerated sets the "tts_generated" field.
func (_u *BookUpdateOne) SetTtsGenerated(v bool) *BookUpdateOne {
	_u.mutation.SetTtsGenerated(v)
	return _u
}

// SetNillableTtsGenerated sets the "tts_generated" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableTtsGenerated(v *bool) *BookUpdateOne {
	if v != nil {
		_u.SetTtsGenerated(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *BookUpdateOne) SetLanguage(v primitive.Language) *BookUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableLanguage(v *primitive.Language) *BookUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetFailed sets the "failed" field.
func (_u *BookUpdateOne) SetFailed(v bool) *BookUpdateOne {
	_u.mutation.SetFailed(v)
	return _u
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableFailed(v *bool) *BookUpdateOne {
	if v != nil {
		_u.SetFailed(*v)
	}
	return _u
}

// SetFailedStage sets the "failed_stage" field.
func (_u *BookUpdateOne) SetFailedStage(v string) *BookUpdateOne {
	_u.mutation.SetFailedStage(v)
	return _u
}

// SetNillableFailedStage sets the "failed_stage" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableFailedStage(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetFailedStage(*v)
	}
	return _u
}

// ClearFailedStage clears the value of the "failed_stage" field.
func (_u *BookUpdateOne) ClearFailedStage() *BookUpdateOne {
	_u.mutation.ClearFailedStage()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *BookUpdateOne) SetErrorMessage(v string) *BookUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableErrorMessage(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *BookUpdateOne) ClearErrorMessage() *BookUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetTokenUsage sets the "token_usage" field.
func (_u *BookUpdateOne) SetTokenUsage(v primitive.TokenUsage) *BookUpdateOne {
	_u.mutation.SetTokenUsage(v)
	return _u
}

// ClearTokenUsage clears the value of the "token_usage" field.
func (_u *BookUpdateOne) ClearTokenUsage() *BookUpdateOne {
	_u.mutation.ClearTokenUsage()
	return _u
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdateOne) Mutation() *BookMutation {
	return _u.mutation
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdateOne) Where(ps ...predicate.Book) *BookUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BookUpdateOne) Select(field string, fields ...string) *BookUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Book entity.
func (_u *BookUpdateOne) Save(ctx context.Context) (*Book, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdateOne) SaveX(ctx context.Context) *Book {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BookUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BookUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := book.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := book.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Book.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := book.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Book.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverURL(); ok {
		if err := book.CoverURLValidator(v); err != nil {
			return &ValidationError{Name: "cover_url", err: fmt.Errorf(`ent: validator failed for field "Book.cover_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := book.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "Book.language": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailedStage(); ok {
		if err := book.FailedStageValidator(v); err != nil {
			return &ValidationError{Name: "failed_stage", err: fmt.Errorf(`ent: validator failed for field "Book.failed_stage": %w`, err)}
		}
	}
	return nil
}

func (_u *BookUpdateOne) sqlSave(ctx context.Context) (_node *Book, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Book.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, book.FieldID)
		for _, f := range fields {
			if !book.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != book.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(book.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(book.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthorNames(); ok {
		_spec.SetField(book.FieldAuthorNames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAuthorNames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, book.FieldAuthorNames, value)
		})
	}
	if _u.mutation.AuthorNamesCleared() {
		_spec.ClearField(book.FieldAuthorNames, field.TypeJSON)
	}
	if value, ok := _u.mutation.AuthorKeys(); ok {
		_spec.SetField(book.FieldAuthorKeys, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAuthorKeys(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, book.FieldAuthorKeys, value)
		})
	}
	if _u.mutation.AuthorKeysCleared() {
		_spec.ClearField(book.FieldAuthorKeys, field.TypeJSON)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(book.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(book.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(book.FieldCoverURL, field.TypeString, value)
	}
	if _u.mutation.CoverURLCleared() {
		_spec.ClearField(book.FieldCoverURL, field.TypeString)
	}
	if value, ok := _u.mutation.Uploaded(); ok {
		_spec.SetField(book.FieldUploaded, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Parsed(); ok {
		_spec.SetField(book.FieldParsed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Prepared(); ok {
		_spec.SetField(book.FieldPrepared, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ScriptGenerated(); ok {
		_spec.SetField(book.FieldScriptGenerated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TtsGenerated(); ok {
		_spec.SetField(book.FieldTtsGenerated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(book.FieldLanguage, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Failed(); ok {
		_spec.SetField(book.FieldFailed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FailedStage(); ok {
		_spec.SetField(book.FieldFailedStage, field.TypeString, value)
	}
	if _u.mutation.FailedStageCleared() {
		_spec.ClearField(book.FieldFailedStage, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(book.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(book.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.TokenUsage(); ok {
		_spec.SetField(book.FieldTokenUsage, field.TypeJSON, value)
	}
	if _u.mutation.TokenUsageCleared() {
		_spec.ClearField(book.FieldTokenUsage, field.TypeJSON)
	}
	_node = &Book{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
