// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"hkorpo/book/internal/primitive"
	"hkorpo/book/pkg/ent/book"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Book is the model entity for the Book schema.
type Book struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// AuthorNames holds the value of the "author_names" field.
	AuthorNames []string `json:"author_names,omitempty"`
	// AuthorKeys holds the value of the "author_keys" field.
	AuthorKeys []string `json:"author_keys,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// CoverURL holds the value of the "cover_url" field.
	CoverURL string `json:"cover_url,omitempty"`
	// Uploaded holds the value of the "uploaded" field.
	Uploaded bool `json:"uploaded,omitempty"`
	// Parsed holds the value of the "parsed" field.
	Parsed bool `json:"parsed,omitempty"`
	// Prepared holds the value of the "prepared" field.
	Prepared bool `json:"prepared,omitempty"`
	// ScriptGenerated holds the value of the "script_generated" field.
	ScriptGenerated bool `json:"script_generated,omitempty"`
	// TtsGenerated holds the value of the "tts_generated" field.
	TtsGenerated bool `json:"tts_generated,omitempty"`
	// Language holds the value of the "language" field.
	Language primitive.Language `json:"language,omitempty"`
	// Failed holds the value of the "failed" field.
	Failed bool `json:"failed,omitempty"`
	// FailedStage holds the value of the "failed_stage" field.
	FailedStage string `json:"failed_stage,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// RetryDisabled holds the value of the "retry_disabled" field.
	RetryDisabled bool `json:"retry_disabled,omitempty"`
	// TokenUsage holds the value of the "token_usage" field.
	TokenUsage   primitive.TokenUsage `json:"token_usage,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Book) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case book.FieldAuthorNames, book.FieldAuthorKeys, book.FieldTokenUsage:
			values[i] = new([]byte)
		case book.FieldUploaded, book.FieldParsed, book.FieldPrepared, book.FieldScriptGenerated, book.FieldTtsGenerated, book.FieldFailed, book.FieldRetryDisabled:
			values[i] = new(sql.NullBool)
		case book.FieldKey, book.FieldTitle, book.FieldDescription, book.FieldCoverURL, book.FieldLanguage, book.FieldFailedStage, book.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case book.FieldCreatedAt, book.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case book.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Book fields.
func (_m *Book) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case book.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case book.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case book.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case book.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case book.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case book.FieldAuthorNames:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field author_names", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AuthorNames); err != nil {
					return fmt.Errorf("unmarshal field author_names: %w", err)
				}
			}
		case book.FieldAuthorKeys:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field author_keys", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AuthorKeys); err != nil {
					return fmt.Errorf("unmarshal field author_keys: %w", err)
				}
			}
		case book.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case book.FieldCoverURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_url", values[i])
			} else if value.Valid {
				_m.CoverURL = value.String
			}
		case book.FieldUploaded:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field uploaded", values[i])
			} else if value.Valid {
				_m.Uploaded = value.Bool
			}
		case book.FieldParsed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field parsed", values[i])
			} else if value.Valid {
				_m.Parsed = value.Bool
			}
		case book.FieldPrepared:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field prepared", values[i])
			} else if value.Valid {
				_m.Prepared = value.Bool
			}
		case book.FieldScriptGenerated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field script_generated", values[i])
			} else if value.Valid {
				_m.ScriptGenerated = value.Bool
			}
		case book.FieldTtsGenerated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field tts_generated", values[i])
			} else if value.Valid {
				_m.TtsGenerated = value.Bool
			}
		case book.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				_m.Language = primitive.Language(value.String)
			}
		case book.FieldFailed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field failed", values[i])
			} else if value.Valid {
				_m.Failed = value.Bool
			}
		case book.FieldFailedStage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failed_stage", values[i])
			} else if value.Valid {
				_m.FailedStage = value.String
			}
		case book.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case book.FieldRetryDisabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field retry_disabled", values[i])
			} else if value.Valid {
				_m.RetryDisabled = value.Bool
			}
		case book.FieldTokenUsage:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field token_usage", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TokenUsage); err != nil {
					return fmt.Errorf("unmarshal field token_usage: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Book.
// This includes values selected through modifiers, order, etc.
func (_m *Book) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Book.
// Note that you need to call Book.Unwrap() before calling this method if this Book
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Book) Update() *BookUpdateOne {
	return NewBookClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Book entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Book) Unwrap() *Book {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Book is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Book) String() string {
	var builder strings.Builder
	builder.WriteString("Book(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("author_names=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthorNames))
	builder.WriteString(", ")
	builder.WriteString("author_keys=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthorKeys))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("cover_url=")
	builder.WriteString(_m.CoverURL)
	builder.WriteString(", ")
	builder.WriteString("uploaded=")
	builder.WriteString(fmt.Sprintf("%v", _m.Uploaded))
	builder.WriteString(", ")
	builder.WriteString("parsed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Parsed))
	builder.WriteString(", ")
	builder.WriteString("prepared=")
	builder.WriteString(fmt.Sprintf("%v", _m.Prepared))
	builder.WriteString(", ")
	builder.WriteString("script_generated=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScriptGenerated))
	builder.WriteString(", ")
	builder.WriteString("tts_generated=")
	builder.WriteString(fmt.Sprintf("%v", _m.TtsGenerated))
	builder.WriteString(", ")
	builder.WriteString("language=")
	builder.WriteString(fmt.Sprintf("%v", _m.Language))
	builder.WriteString(", ")
	builder.WriteString("failed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Failed))
	builder.WriteString(", ")
	builder.WriteString("failed_stage=")
	builder.WriteString(_m.FailedStage)
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("retry_disabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryDisabled))
	builder.WriteString(", ")
	builder.WriteString("token_usage=")
	builder.WriteString(fmt.Sprintf("%v", _m.TokenUsage))
	builder.WriteByte(')')
	return builder.String()
}

// Books is a parsable slice of Book.
type Books []*Book
