// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"hkorpo/book/internal/primitive"
	"hkorpo/book/pkg/ent/subscription"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Subscription is the model entity for the Subscription schema.
type Subscription struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// StripeCustomerID holds the value of the "stripe_customer_id" field.
	StripeCustomerID string `json:"stripe_customer_id,omitempty"`
	// StripeSubscriptionID holds the value of the "stripe_subscription_id" field.
	StripeSubscriptionID string `json:"stripe_subscription_id,omitempty"`
	// Status holds the value of the "status" field.
	Status primitive.SubscriptionStatus `json:"status,omitempty"`
	// CurrentPeriodEnd holds the value of the "current_period_end" field.
	CurrentPeriodEnd *time.Time `json:"current_period_end,omitempty"`
	// CancelAtPeriodEnd holds the value of the "cancel_at_period_end" field.
	CancelAtPeriodEnd bool `json:"cancel_at_period_end,omitempty"`
	// RevenuecatActive holds the value of the "revenuecat_active" field.
	RevenuecatActive bool `json:"revenuecat_active,omitempty"`
	// RevenuecatExpiresAt holds the value of the "revenuecat_expires_at" field.
	RevenuecatExpiresAt *time.Time `json:"revenuecat_expires_at,omitempty"`
	// RevenuecatStore holds the value of the "revenuecat_store" field.
	RevenuecatStore string `json:"revenuecat_store,omitempty"`
	// RevenuecatEntitlementID holds the value of the "revenuecat_entitlement_id" field.
	RevenuecatEntitlementID string `json:"revenuecat_entitlement_id,omitempty"`
	// RevenuecatOriginalTransactionID holds the value of the "revenuecat_original_transaction_id" field.
	RevenuecatOriginalTransactionID string `json:"revenuecat_original_transaction_id,omitempty"`
	selectValues                    sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Subscription) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscription.FieldCancelAtPeriodEnd, subscription.FieldRevenuecatActive:
			values[i] = new(sql.NullBool)
		case subscription.FieldStripeCustomerID, subscription.FieldStripeSubscriptionID, subscription.FieldStatus, subscription.FieldRevenuecatStore, subscription.FieldRevenuecatEntitlementID, subscription.FieldRevenuecatOriginalTransactionID:
			values[i] = new(sql.NullString)
		case subscription.FieldCreatedAt, subscription.FieldUpdatedAt, subscription.FieldCurrentPeriodEnd, subscription.FieldRevenuecatExpiresAt:
			values[i] = new(sql.NullTime)
		case subscription.FieldID, subscription.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Subscription fields.
func (_m *Subscription) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscription.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case subscription.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscription.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case subscription.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case subscription.FieldStripeCustomerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stripe_customer_id", values[i])
			} else if value.Valid {
				_m.StripeCustomerID = value.String
			}
		case subscription.FieldStripeSubscriptionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stripe_subscription_id", values[i])
			} else if value.Valid {
				_m.StripeSubscriptionID = value.String
			}
		case subscription.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = primitive.SubscriptionStatus(value.String)
			}
		case subscription.FieldCurrentPeriodEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field current_period_end", values[i])
			} else if value.Valid {
				_m.CurrentPeriodEnd = new(time.Time)
				*_m.CurrentPeriodEnd = value.Time
			}
		case subscription.FieldCancelAtPeriodEnd:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field cancel_at_period_end", values[i])
			} else if value.Valid {
				_m.CancelAtPeriodEnd = value.Bool
			}
		case subscription.FieldRevenuecatActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field revenuecat_active", values[i])
			} else if value.Valid {
				_m.RevenuecatActive = value.Bool
			}
		case subscription.FieldRevenuecatExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revenuecat_expires_at", values[i])
			} else if value.Valid {
				_m.RevenuecatExpiresAt = new(time.Time)
				*_m.RevenuecatExpiresAt = value.Time
			}
		case subscription.FieldRevenuecatStore:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field revenuecat_store", values[i])
			} else if value.Valid {
				_m.RevenuecatStore = value.String
			}
		case subscription.FieldRevenuecatEntitlementID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field revenuecat_entitlement_id", values[i])
			} else if value.Valid {
				_m.RevenuecatEntitlementID = value.String
			}
		case subscription.FieldRevenuecatOriginalTransactionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field revenuecat_original_transaction_id", values[i])
			} else if value.Valid {
				_m.RevenuecatOriginalTransactionID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Subscription.
// This includes values selected through modifiers, order, etc.
func (_m *Subscription) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Subscription.
// Note that you need to call Subscription.Unwrap() before calling this method if this Subscription
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Subscription) Update() *SubscriptionUpdateOne {
	return NewSubscriptionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Subscription entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Subscription) Unwrap() *Subscription {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Subscription is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Subscription) String() string {
	var builder strings.Builder
	builder.WriteString("Subscription(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("stripe_customer_id=")
	builder.WriteString(_m.StripeCustomerID)
	builder.WriteString(", ")
	builder.WriteString("stripe_subscription_id=")
	builder.WriteString(_m.StripeSubscriptionID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.CurrentPeriodEnd; v != nil {
		builder.WriteString("current_period_end=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("cancel_at_period_end=")
	builder.WriteString(fmt.Sprintf("%v", _m.CancelAtPeriodEnd))
	builder.WriteString(", ")
	builder.WriteString("revenuecat_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.RevenuecatActive))
	builder.WriteString(", ")
	if v := _m.RevenuecatExpiresAt; v != nil {
		builder.WriteString("revenuecat_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("revenuecat_store=")
	builder.WriteString(_m.RevenuecatStore)
	builder.WriteString(", ")
	builder.WriteString("revenuecat_entitlement_id=")
	builder.WriteString(_m.RevenuecatEntitlementID)
	builder.WriteString(", ")
	builder.WriteString("revenuecat_original_transaction_id=")
	builder.WriteString(_m.RevenuecatOriginalTransactionID)
	builder.WriteByte(')')
	return builder.String()
}

// Subscriptions is a parsable slice of Subscription.
type Subscriptions []*Subscription
