// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hkorpo/book/internal/primitive"
	"hkorpo/book/pkg/ent/predicate"
	"hkorpo/book/pkg/ent/subscription"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SubscriptionUpdate is the builder for updating Subscription entities.
type SubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionMutation
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (_u *SubscriptionUpdate) Where(ps ...predicate.Subscription) *SubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionUpdate) SetUpdatedAt(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionUpdate) SetUserID(v uuid.UUID) *SubscriptionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableUserID(v *uuid.UUID) *SubscriptionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (_u *SubscriptionUpdate) SetStripeCustomerID(v string) *SubscriptionUpdate {
	_u.mutation.SetStripeCustomerID(v)
	return _u
}

// SetNillableStripeCustomerID sets the "stripe_customer_id" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableStripeCustomerID(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetStripeCustomerID(*v)
	}
	return _u
}

// ClearStripeCustomerID clears the value of the "stripe_customer_id" field.
func (_u *SubscriptionUpdate) ClearStripeCustomerID() *SubscriptionUpdate {
	_u.mutation.ClearStripeCustomerID()
	return _u
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (_u *SubscriptionUpdate) SetStripeSubscriptionID(v string) *SubscriptionUpdate {
	_u.mutation.SetStripeSubscriptionID(v)
	return _u
}

// SetNillableStripeSubscriptionID sets the "stripe_subscription_id" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableStripeSubscriptionID(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetStripeSubscriptionID(*v)
	}
	return _u
}

// ClearStripeSubscriptionID clears the value of the "stripe_subscription_id" field.
func (_u *SubscriptionUpdate) ClearStripeSubscriptionID() *SubscriptionUpdate {
	_u.mutation.ClearStripeSubscriptionID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionUpdate) SetStatus(v primitive.SubscriptionStatus) *SubscriptionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableStatus(v *primitive.SubscriptionStatus) *SubscriptionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (_u *SubscriptionUpdate) SetCurrentPeriodEnd(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetCurrentPeriodEnd(v)
	return _u
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableCurrentPeriodEnd(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetCurrentPeriodEnd(*v)
	}
	return _u
}

// ClearCurrentPeriodEnd clears the value of the "current_period_end" field.
func (_u *SubscriptionUpdate) ClearCurrentPeriodEnd() *SubscriptionUpdate {
	_u.mutation.ClearCurrentPeriodEnd()
	return _u
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (_u *SubscriptionUpdate) SetCancelAtPeriodEnd(v bool) *SubscriptionUpdate {
	_u.mutation.SetCancelAtPeriodEnd(v)
	return _u
}

// SetNillableCancelAtPeriodEnd sets the "cancel_at_period_end" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableCancelAtPeriodEnd(v *bool) *SubscriptionUpdate {
	if v != nil {
		_u.SetCancelAtPeriodEnd(*v)
	}
	return _u
}

// SetRevenuecatActive sets the "revenuecat_active" field.
func (_u *SubscriptionUpdate) SetRevenuecatActive(v bool) *SubscriptionUpdate {
	_u.mutation.SetRevenuecatActive(v)
	return _u
}

// SetNillableRevenuecatActive sets the "revenuecat_active" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableRevenuecatActive(v *bool) *SubscriptionUpdate {
	if v != nil {
		_u.SetRevenuecatActive(*v)
	}
	return _u
}

// SetRevenuecatExpiresAt sets the "revenuecat_expires_at" field.
func (_u *SubscriptionUpdate) SetRevenuecatExpiresAt(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetRevenuecatExpiresAt(v)
	return _u
}

// SetNillableRevenuecatExpiresAt sets the "revenuecat_expires_at" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableRevenuecatExpiresAt(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetRevenuecatExpiresAt(*v)
	}
	return _u
}

// ClearRevenuecatExpiresAt clears the value of the "revenuecat_expires_at" field.
func (_u *SubscriptionUpdate) ClearRevenuecatExpiresAt() *SubscriptionUpdate {
	_u.mutation.ClearRevenuecatExpiresAt()
	return _u
}

// SetRevenuecatStore sets the "revenuecat_store" field.
func (_u *SubscriptionUpdate) SetRevenuecatStore(v string) *SubscriptionUpdate {
	_u.mutation.SetRevenuecatStore(v)
	return _u
}

// SetNillableRevenuecatStore sets the "revenuecat_store" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableRevenuecatStore(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetRevenuecatStore(*v)
	}
	return _u
}

// ClearRevenuecatStore clears the value of the "revenuecat_store" field.
func (_u *SubscriptionUpdate) ClearRevenuecatStore() *SubscriptionUpdate {
	_u.mutation.ClearRevenuecatStore()
	return _u
}

// SetRevenuecatEntitlementID sets the "revenuecat_entitlement_id" field.
func (_u *SubscriptionUpdate) SetRevenuecatEntitlementID(v string) *SubscriptionUpdate {
	_u.mutation.SetRevenuecatEntitlementID(v)
	return _u
}

// SetNillableRevenuecatEntitlementID sets the "revenuecat_entitlement_id" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableRevenuecatEntitlementID(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetRevenuecatEntitlementID(*v)
	}
	return _u
}

// ClearRevenuecatEntitlementID clears the value of the "revenuecat_entitlement_id" field.
func (_u *SubscriptionUpdate) ClearRevenuecatEntitlementID() *SubscriptionUpdate {
	_u.mutation.ClearRevenuecatEntitlementID()
	return _u
}

// SetRevenuecatOriginalTransactionID sets the "revenuecat_original_transaction_id" field.
func (_u *SubscriptionUpdate) SetRevenuecatOriginalTransactionID(v string) *SubscriptionUpdate {
	_u.mutation.SetRevenuecatOriginalTransactionID(v)
	return _u
}

// SetNillableRevenuecatOriginalTransactionID sets the "revenuecat_original_transaction_id" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableRevenuecatOriginalTransactionID(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetRevenuecatOriginalTransactionID(*v)
	}
	return _u
}

// ClearRevenuecatOriginalTransactionID clears the value of the "revenuecat_original_transaction_id" field.
func (_u *SubscriptionUpdate) ClearRevenuecatOriginalTransactionID() *SubscriptionUpdate {
	_u.mutation.ClearRevenuecatOriginalTransactionID()
	return _u
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_u *SubscriptionUpdate) Mutation() *SubscriptionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionUpdate) check() error {
	if v, ok := _u.mutation.StripeCustomerID(); ok {
		if err := subscription.StripeCustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_customer_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.stripe_customer_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StripeSubscriptionID(); ok {
		if err := subscription.StripeSubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_subscription_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.stripe_subscription_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Subscription.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RevenuecatStore(); ok {
		if err := subscription.RevenuecatStoreValidator(v); err != nil {
			return &ValidationError{Name: "revenuecat_store", err: fmt.Errorf(`ent: validator failed for field "Subscription.revenuecat_store": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RevenuecatEntitlementID(); ok {
		if err := subscription.RevenuecatEntitlementIDValidator(v); err != nil {
			return &ValidationError{Name: "revenuecat_entitlement_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.revenuecat_entitlement_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RevenuecatOriginalTransactionID(); ok {
		if err := subscription.RevenuecatOriginalTransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "revenuecat_original_transaction_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.revenuecat_original_transaction_id": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(subscription.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.StripeCustomerID(); ok {
		_spec.SetField(subscription.FieldStripeCustomerID, field.TypeString, value)
	}
	if _u.mutation.StripeCustomerIDCleared() {
		_spec.ClearField(subscription.FieldStripeCustomerID, field.TypeString)
	}
	if value, ok := _u.mutation.StripeSubscriptionID(); ok {
		_spec.SetField(subscription.FieldStripeSubscriptionID, field.TypeString, value)
	}
	if _u.mutation.StripeSubscriptionIDCleared() {
		_spec.ClearField(subscription.FieldStripeSubscriptionID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodEnd, field.TypeTime, value)
	}
	if _u.mutation.CurrentPeriodEndCleared() {
		_spec.ClearField(subscription.FieldCurrentPeriodEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.CancelAtPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCancelAtPeriodEnd, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RevenuecatActive(); ok {
		_spec.SetField(subscription.FieldRevenuecatActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RevenuecatExpiresAt(); ok {
		_spec.SetField(subscription.FieldRevenuecatExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.RevenuecatExpiresAtCleared() {
		_spec.ClearField(subscription.FieldRevenuecatExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevenuecatStore(); ok {
		_spec.SetField(subscription.FieldRevenuecatStore, field.TypeString, value)
	}
	if _u.mutation.RevenuecatStoreCleared() {
		_spec.ClearField(subscription.FieldRevenuecatStore, field.TypeString)
	}
	if value, ok := _u.mutation.RevenuecatEntitlementID(); ok {
		_spec.SetField(subscription.FieldRevenuecatEntitlementID, field.TypeString, value)
	}
	if _u.mutation.RevenuecatEntitlementIDCleared() {
		_spec.ClearField(subscription.FieldRevenuecatEntitlementID, field.TypeString)
	}
	if value, ok := _u.mutation.RevenuecatOriginalTransactionID(); ok {
		_spec.SetField(subscription.FieldRevenuecatOriginalTransactionID, field.TypeString, value)
	}
	if _u.mutation.RevenuecatOriginalTransactionIDCleared() {
		_spec.ClearField(subscription.FieldRevenuecatOriginalTransactionID, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionUpdateOne is the builder for updating a single Subscription entity.
type SubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionUpdateOne) SetUserID(v uuid.UUID) *SubscriptionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableUserID(v *uuid.UUID) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (_u *SubscriptionUpdateOne) SetStripeCustomerID(v string) *SubscriptionUpdateOne {
	_u.mutation.SetStripeCustomerID(v)
	return _u
}

// SetNillableStripeCustomerID sets the "stripe_customer_id" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableStripeCustomerID(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetStripeCustomerID(*v)
	}
	return _u
}

// ClearStripeCustomerID clears the value of the "stripe_customer_id" field.
func (_u *SubscriptionUpdateOne) ClearStripeCustomerID() *SubscriptionUpdateOne {
	_u.mutation.ClearStripeCustomerID()
	return _u
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (_u *SubscriptionUpdateOne) SetStripeSubscriptionID(v string) *SubscriptionUpdateOne {
	_u.mutation.SetStripeSubscriptionID(v)
	return _u
}

// SetNillableStripeSubscriptionID sets the "stripe_subscription_id" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableStripeSubscriptionID(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetStripeSubscriptionID(*v)
	}
	return _u
}

// ClearStripeSubscriptionID clears the value of the "stripe_subscription_id" field.
func (_u *SubscriptionUpdateOne) ClearStripeSubscriptionID() *SubscriptionUpdateOne {
	_u.mutation.ClearStripeSubscriptionID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionUpdateOne) SetStatus(v primitive.SubscriptionStatus) *SubscriptionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableStatus(v *primitive.SubscriptionStatus) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (_u *SubscriptionUpdateOne) SetCurrentPeriodEnd(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetCurrentPeriodEnd(v)
	return _u
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableCurrentPeriodEnd(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetCurrentPeriodEnd(*v)
	}
	return _u
}

// ClearCurrentPeriodEnd clears the value of the "current_period_end" field.
func (_u *SubscriptionUpdateOne) ClearCurrentPeriodEnd() *SubscriptionUpdateOne {
	_u.mutation.ClearCurrentPeriodEnd()
	return _u
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (_u *SubscriptionUpdateOne) SetCancelAtPeriodEnd(v bool) *SubscriptionUpdateOne {
	_u.mutation.SetCancelAtPeriodEnd(v)
	return _u
}

// SetNillableCancelAtPeriodEnd sets the "cancel_at_period_end" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableCancelAtPeriodEnd(v *bool) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetCancelAtPeriodEnd(*v)
	}
	return _u
}

// SetRevenuecatActive sets the "revenuecat_active" field.
func (_u *SubscriptionUpdateOne) SetRevenuecatActive(v bool) *SubscriptionUpdateOne {
	_u.mutation.SetRevenuecatActive(v)
	return _u
}

// SetNillableRevenuecatActive sets the "revenuecat_active" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableRevenuecatActive(v *bool) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetRevenuecatActive(*v)
	}
	return _u
}

// SetRevenuecatExpiresAt sets the "revenuecat_expires_at" field.
func (_u *SubscriptionUpdateOne) SetRevenuecatExpiresAt(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetRevenuecatExpiresAt(v)
	return _u
}

// SetNillableRevenuecatExpiresAt sets the "revenuecat_expires_at" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableRevenuecatExpiresAt(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetRevenuecatExpiresAt(*v)
	}
	return _u
}

// ClearRevenuecatExpiresAt clears the value of the "revenuecat_expires_at" field.
func (_u *SubscriptionUpdateOne) ClearRevenuecatExpiresAt() *SubscriptionUpdateOne {
	_u.mutation.ClearRevenuecatExpiresAt()
	return _u
}

// SetRevenuecatStore sets the "revenuecat_store" field.
func (_u *SubscriptionUpdateOne) SetRevenuecatStore(v string) *SubscriptionUpdateOne {
	_u.mutation.SetRevenuecatStore(v)
	return _u
}

// SetNillableRevenuecatStore sets the "revenuecat_store" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableRevenuecatStore(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetRevenuecatStore(*v)
	}
	return _u
}

// ClearRevenuecatStore clears the value of the "revenuecat_store" field.
func (_u *SubscriptionUpdateOne) ClearRevenuecatStore() *SubscriptionUpdateOne {
	_u.mutation.ClearRevenuecatStore()
	return _u
}

// SetRevenuecatEntitlementID sets the "revenuecat_entitlement_id" field.
func (_u *SubscriptionUpdateOne) SetRevenuecatEntitlementID(v string) *SubscriptionUpdateOne {
	_u.mutation.SetRevenuecatEntitlementID(v)
	return _u
}

// SetNillableRevenuecatEntitlementID sets the "revenuecat_entitlement_id" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableRevenuecatEntitlementID(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetRevenuecatEntitlementID(*v)
	}
	return _u
}

// ClearRevenuecatEntitlementID clears the value of the "revenuecat_entitlement_id" field.
func (_u *SubscriptionUpdateOne) ClearRevenuecatEntitlementID() *SubscriptionUpdateOne {
	_u.mutation.ClearRevenuecatEntitlementID()
	return _u
}

// SetRevenuecatOriginalTransactionID sets the "revenuecat_original_transaction_id" field.
func (_u *SubscriptionUpdateOne) SetRevenuecatOriginalTransactionID(v string) *SubscriptionUpdateOne {
	_u.mutation.SetRevenuecatOriginalTransactionID(v)
	return _u
}

// SetNillableRevenuecatOriginalTransactionID sets the "revenuecat_original_transaction_id" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableRevenuecatOriginalTransactionID(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetRevenuecatOriginalTransactionID(*v)
	}
	return _u
}

// ClearRevenuecatOriginalTransactionID clears the value of the "revenuecat_original_transaction_id" field.
func (_u *SubscriptionUpdateOne) ClearRevenuecatOriginalTransactionID() *SubscriptionUpdateOne {
	_u.mutation.ClearRevenuecatOriginalTransactionID()
	return _u
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_u *SubscriptionUpdateOne) Mutation() *SubscriptionMutation {
	return _u.mutation
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (_u *SubscriptionUpdateOne) Where(ps ...predicate.Subscription) *SubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionUpdateOne) Select(field string, fields ...string) *SubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Subscription entity.
func (_u *SubscriptionUpdateOne) Save(ctx context.Context) (*Subscription, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionUpdateOne) SaveX(ctx context.Context) *Subscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionUpdateOne) check() error {
	if v, ok := _u.mutation.StripeCustomerID(); ok {
		if err := subscription.StripeCustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_customer_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.stripe_customer_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StripeSubscriptionID(); ok {
		if err := subscription.StripeSubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_subscription_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.stripe_subscription_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Subscription.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RevenuecatStore(); ok {
		if err := subscription.RevenuecatStoreValidator(v); err != nil {
			return &ValidationError{Name: "revenuecat_store", err: fmt.Errorf(`ent: validator failed for field "Subscription.revenuecat_store": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RevenuecatEntitlementID(); ok {
		if err := subscription.RevenuecatEntitlementIDValidator(v); err != nil {
			return &ValidationError{Name: "revenuecat_entitlement_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.revenuecat_entitlement_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RevenuecatOriginalTransactionID(); ok {
		if err := subscription.RevenuecatOriginalTransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "revenuecat_original_transaction_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.revenuecat_original_transaction_id": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *Subscription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Subscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscription.FieldID)
		for _, f := range fields {
			if !subscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(subscription.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.StripeCustomerID(); ok {
		_spec.SetField(subscription.FieldStripeCustomerID, field.TypeString, value)
	}
	if _u.mutation.StripeCustomerIDCleared() {
		_spec.ClearField(subscription.FieldStripeCustomerID, field.TypeString)
	}
	if value, ok := _u.mutation.StripeSubscriptionID(); ok {
		_spec.SetField(subscription.FieldStripeSubscriptionID, field.TypeString, value)
	}
	if _u.mutation.StripeSubscriptionIDCleared() {
		_spec.ClearField(subscription.FieldStripeSubscriptionID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodEnd, field.TypeTime, value)
	}
	if _u.mutation.CurrentPeriodEndCleared() {
		_spec.ClearField(subscription.FieldCurrentPeriodEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.CancelAtPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCancelAtPeriodEnd, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RevenuecatActive(); ok {
		_spec.SetField(subscription.FieldRevenuecatActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RevenuecatExpiresAt(); ok {
		_spec.SetField(subscription.FieldRevenuecatExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.RevenuecatExpiresAtCleared() {
		_spec.ClearField(subscription.FieldRevenuecatExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevenuecatStore(); ok {
		_spec.SetField(subscription.FieldRevenuecatStore, field.TypeString, value)
	}
	if _u.mutation.RevenuecatStoreCleared() {
		_spec.ClearField(subscription.FieldRevenuecatStore, field.TypeString)
	}
	if value, ok := _u.mutation.RevenuecatEntitlementID(); ok {
		_spec.SetField(subscription.FieldRevenuecatEntitlementID, field.TypeString, value)
	}
	if _u.mutation.RevenuecatEntitlementIDCleared() {
		_spec.ClearField(subscription.FieldRevenuecatEntitlementID, field.TypeString)
	}
	if value, ok := _u.mutation.RevenuecatOriginalTransactionID(); ok {
		_spec.SetField(subscription.FieldRevenuecatOriginalTransactionID, field.TypeString, value)
	}
	if _u.mutation.RevenuecatOriginalTransactionIDCleared() {
		_spec.ClearField(subscription.FieldRevenuecatOriginalTransactionID, field.TypeString)
	}
	_node = &Subscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
