// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hkorpo/book/internal/primitive"
	"hkorpo/book/pkg/ent/subscription"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SubscriptionCreate is the builder for creating a Subscription entity.
type SubscriptionCreate struct {
	config
	mutation *SubscriptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionCreate) SetCreatedAt(v time.Time) *SubscriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionCreate) SetUpdatedAt(v time.Time) *SubscriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SubscriptionCreate) SetUserID(v uuid.UUID) *SubscriptionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (_c *SubscriptionCreate) SetStripeCustomerID(v string) *SubscriptionCreate {
	_c.mutation.SetStripeCustomerID(v)
	return _c
}

// SetNillableStripeCustomerID sets the "stripe_customer_id" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableStripeCustomerID(v *string) *SubscriptionCreate {
	if v != nil {
		_c.SetStripeCustomerID(*v)
	}
	return _c
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (_c *SubscriptionCreate) SetStripeSubscriptionID(v string) *SubscriptionCreate {
	_c.mutation.SetStripeSubscriptionID(v)
	return _c
}

// SetNillableStripeSubscriptionID sets the "stripe_subscription_id" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableStripeSubscriptionID(v *string) *SubscriptionCreate {
	if v != nil {
		_c.SetStripeSubscriptionID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubscriptionCreate) SetStatus(v primitive.SubscriptionStatus) *SubscriptionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableStatus(v *primitive.SubscriptionStatus) *SubscriptionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (_c *SubscriptionCreate) SetCurrentPeriodEnd(v time.Time) *SubscriptionCreate {
	_c.mutation.SetCurrentPeriodEnd(v)
	return _c
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableCurrentPeriodEnd(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetCurrentPeriodEnd(*v)
	}
	return _c
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (_c *SubscriptionCreate) SetCancelAtPeriodEnd(v bool) *SubscriptionCreate {
	_c.mutation.SetCancelAtPeriodEnd(v)
	return _c
}

// SetNillableCancelAtPeriodEnd sets the "cancel_at_period_end" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableCancelAtPeriodEnd(v *bool) *SubscriptionCreate {
	if v != nil {
		_c.SetCancelAtPeriodEnd(*v)
	}
	return _c
}

// SetRevenuecatActive sets the "revenuecat_active" field.
func (_c *SubscriptionCreate) SetRevenuecatActive(v bool) *SubscriptionCreate {
	_c.mutation.SetRevenuecatActive(v)
	return _c
}

// SetNillableRevenuecatActive sets the "revenuecat_active" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableRevenuecatActive(v *bool) *SubscriptionCreate {
	if v != nil {
		_c.SetRevenuecatActive(*v)
	}
	return _c
}

// SetRevenuecatExpiresAt sets the "revenuecat_expires_at" field.
func (_c *SubscriptionCreate) SetRevenuecatExpiresAt(v time.Time) *SubscriptionCreate {
	_c.mutation.SetRevenuecatExpiresAt(v)
	return _c
}

// SetNillableRevenuecatExpiresAt sets the "revenuecat_expires_at" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableRevenuecatExpiresAt(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetRevenuecatExpiresAt(*v)
	}
	return _c
}

// SetRevenuecatStore sets the "revenuecat_store" field.
func (_c *SubscriptionCreate) SetRevenuecatStore(v string) *SubscriptionCreate {
	_c.mutation.SetRevenuecatStore(v)
	return _c
}

// SetNillableRevenuecatStore sets the "revenuecat_store" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableRevenuecatStore(v *string) *SubscriptionCreate {
	if v != nil {
		_c.SetRevenuecatStore(*v)
	}
	return _c
}

// SetRevenuecatEntitlementID sets the "revenuecat_entitlement_id" field.
func (_c *SubscriptionCreate) SetRevenuecatEntitlementID(v string) *SubscriptionCreate {
	_c.mutation.SetRevenuecatEntitlementID(v)
	return _c
}

// SetNillableRevenuecatEntitlementID sets the "revenuecat_entitlement_id" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableRevenuecatEntitlementID(v *string) *SubscriptionCreate {
	if v != nil {
		_c.SetRevenuecatEntitlementID(*v)
	}
	return _c
}

// SetRevenuecatOriginalTransactionID sets the "revenuecat_original_transaction_id" field.
func (_c *SubscriptionCreate) SetRevenuecatOriginalTransactionID(v string) *SubscriptionCreate {
	_c.mutation.SetRevenuecatOriginalTransactionID(v)
	return _c
}

// SetNillableRevenuecatOriginalTransactionID sets the "revenuecat_original_transaction_id" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableRevenuecatOriginalTransactionID(v *string) *SubscriptionCreate {
	if v != nil {
		_c.SetRevenuecatOriginalTransactionID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SubscriptionCreate) SetID(v uuid.UUID) *SubscriptionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableID(v *uuid.UUID) *SubscriptionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_c *SubscriptionCreate) Mutation() *SubscriptionMutation {
	return _c.mutation
}

// Save creates the Subscription in the database.
func (_c *SubscriptionCreate) Save(ctx context.Context) (*Subscription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionCreate) SaveX(ctx context.Context) *Subscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := subscription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := subscription.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CancelAtPeriodEnd(); !ok {
		v := subscription.DefaultCancelAtPeriodEnd
		_c.mutation.SetCancelAtPeriodEnd(v)
	}
	if _, ok := _c.mutation.RevenuecatActive(); !ok {
		v := subscription.DefaultRevenuecatActive
		_c.mutation.SetRevenuecatActive(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := subscription.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Subscription.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Subscription.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Subscription.user_id"`)}
	}
	if v, ok := _c.mutation.StripeCustomerID(); ok {
		if err := subscription.StripeCustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_customer_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.stripe_customer_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.StripeSubscriptionID(); ok {
		if err := subscription.StripeSubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_subscription_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.stripe_subscription_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Subscription.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := subscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Subscription.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CancelAtPeriodEnd(); !ok {
		return &ValidationError{Name: "cancel_at_period_end", err: errors.New(`ent: missing required field "Subscription.cancel_at_period_end"`)}
	}
	if _, ok := _c.mutation.RevenuecatActive(); !ok {
		return &ValidationError{Name: "revenuecat_active", err: errors.New(`ent: missing required field "Subscription.revenuecat_active"`)}
	}
	if v, ok := _c.mutation.RevenuecatStore(); ok {
		if err := subscription.RevenuecatStoreValidator(v); err != nil {
			return &ValidationError{Name: "revenuecat_store", err: fmt.Errorf(`ent: validator failed for field "Subscription.revenuecat_store": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RevenuecatEntitlementID(); ok {
		if err := subscription.RevenuecatEntitlementIDValidator(v); err != nil {
			return &ValidationError{Name: "revenuecat_entitlement_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.revenuecat_entitlement_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RevenuecatOriginalTransactionID(); ok {
		if err := subscription.RevenuecatOriginalTransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "revenuecat_original_transaction_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.revenuecat_original_transaction_id": %w`, err)}
		}
	}
	return nil
}

func (_c *SubscriptionCreate) sqlSave(ctx context.Context) (*Subscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionCreate) createSpec() (*Subscription, *sqlgraph.CreateSpec) {
	var (
		_node = &Subscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscription.Table, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(subscription.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.StripeCustomerID(); ok {
		_spec.SetField(subscription.FieldStripeCustomerID, field.TypeString, value)
		_node.StripeCustomerID = value
	}
	if value, ok := _c.mutation.StripeSubscriptionID(); ok {
		_spec.SetField(subscription.FieldStripeSubscriptionID, field.TypeString, value)
		_node.StripeSubscriptionID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodEnd, field.TypeTime, value)
		_node.CurrentPeriodEnd = &value
	}
	if value, ok := _c.mutation.CancelAtPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCancelAtPeriodEnd, field.TypeBool, value)
		_node.CancelAtPeriodEnd = value
	}
	if value, ok := _c.mutation.RevenuecatActive(); ok {
		_spec.SetField(subscription.FieldRevenuecatActive, field.TypeBool, value)
		_node.RevenuecatActive = value
	}
	if value, ok := _c.mutation.RevenuecatExpiresAt(); ok {
		_spec.SetField(subscription.FieldRevenuecatExpiresAt, field.TypeTime, value)
		_node.RevenuecatExpiresAt = &value
	}
	if value, ok := _c.mutation.RevenuecatStore(); ok {
		_spec.SetField(subscription.FieldRevenuecatStore, field.TypeString, value)
		_node.RevenuecatStore = value
	}
	if value, ok := _c.mutation.RevenuecatEntitlementID(); ok {
		_spec.SetField(subscription.FieldRevenuecatEntitlementID, field.TypeString, value)
		_node.RevenuecatEntitlementID = value
	}
	if value, ok := _c.mutation.RevenuecatOriginalTransactionID(); ok {
		_spec.SetField(subscription.FieldRevenuecatOriginalTransactionID, field.TypeString, value)
		_node.RevenuecatOriginalTransactionID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Subscription.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionUpsertOne {
	_c.conflict = opts
	return &SubscriptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Subscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionCreate) OnConflictColumns(columns ...string) *SubscriptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionUpsertOne is the builder for "upsert"-ing
	//  one Subscription node.
	SubscriptionUpsertOne struct {
		create *SubscriptionCreate
	}

	// SubscriptionUpsert is the "OnConflict" setter.
	SubscriptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionUpsert) SetUpdatedAt(v time.Time) *SubscriptionUpsert {
	u.Set(subscription.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateUpdatedAt() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionUpsert) SetUserID(v uuid.UUID) *SubscriptionUpsert {
	u.Set(subscription.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateUserID() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldUserID)
	return u
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (u *SubscriptionUpsert) SetStripeCustomerID(v string) *SubscriptionUpsert {
	u.Set(subscription.FieldStripeCustomerID, v)
	return u
}

// UpdateStripeCustomerID sets the "stripe_customer_id" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateStripeCustomerID() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldStripeCustomerID)
	return u
}

// ClearStripeCustomerID clears the value of the "stripe_customer_id" field.
func (u *SubscriptionUpsert) ClearStripeCustomerID() *SubscriptionUpsert {
	u.SetNull(subscription.FieldStripeCustomerID)
	return u
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (u *SubscriptionUpsert) SetStripeSubscriptionID(v string) *SubscriptionUpsert {
	u.Set(subscription.FieldStripeSubscriptionID, v)
	return u
}

// UpdateStripeSubscriptionID sets the "stripe_subscription_id" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateStripeSubscriptionID() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldStripeSubscriptionID)
	return u
}

// ClearStripeSubscriptionID clears the value of the "stripe_subscription_id" field.
func (u *SubscriptionUpsert) ClearStripeSubscriptionID() *SubscriptionUpsert {
	u.SetNull(subscription.FieldStripeSubscriptionID)
	return u
}

// SetStatus sets the "status" field.
func (u *SubscriptionUpsert) SetStatus(v primitive.SubscriptionStatus) *SubscriptionUpsert {
	u.Set(subscription.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateStatus() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldStatus)
	return u
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (u *SubscriptionUpsert) SetCurrentPeriodEnd(v time.Time) *SubscriptionUpsert {
	u.Set(subscription.FieldCurrentPeriodEnd, v)
	return u
}

// UpdateCurrentPeriodEnd sets the "current_period_end" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateCurrentPeriodEnd() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldCurrentPeriodEnd)
	return u
}

// ClearCurrentPeriodEnd clears the value of the "current_period_end" field.
func (u *SubscriptionUpsert) ClearCurrentPeriodEnd() *SubscriptionUpsert {
	u.SetNull(subscription.FieldCurrentPeriodEnd)
	return u
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (u *SubscriptionUpsert) SetCancelAtPeriodEnd(v bool) *SubscriptionUpsert {
	u.Set(subscription.FieldCancelAtPeriodEnd, v)
	return u
}

// UpdateCancelAtPeriodEnd sets the "cancel_at_period_end" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateCancelAtPeriodEnd() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldCancelAtPeriodEnd)
	return u
}

// SetRevenuecatActive sets the "revenuecat_active" field.
func (u *SubscriptionUpsert) SetRevenuecatActive(v bool) *SubscriptionUpsert {
	u.Set(subscription.FieldRevenuecatActive, v)
	return u
}

// UpdateRevenuecatActive sets the "revenuecat_active" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateRevenuecatActive() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldRevenuecatActive)
	return u
}

// SetRevenuecatExpiresAt sets the "revenuecat_expires_at" field.
func (u *SubscriptionUpsert) SetRevenuecatExpiresAt(v time.Time) *SubscriptionUpsert {
	u.Set(subscription.FieldRevenuecatExpiresAt, v)
	return u
}

// UpdateRevenuecatExpiresAt sets the "revenuecat_expires_at" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateRevenuecatExpiresAt() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldRevenuecatExpiresAt)
	return u
}

// ClearRevenuecatExpiresAt clears the value of the "revenuecat_expires_at" field.
func (u *SubscriptionUpsert) ClearRevenuecatExpiresAt() *SubscriptionUpsert {
	u.SetNull(subscription.FieldRevenuecatExpiresAt)
	return u
}

// SetRevenuecatStore sets the "revenuecat_store" field.
func (u *SubscriptionUpsert) SetRevenuecatStore(v string) *SubscriptionUpsert {
	u.Set(subscription.FieldRevenuecatStore, v)
	return u
}

// UpdateRevenuecatStore sets the "revenuecat_store" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateRevenuecatStore() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldRevenuecatStore)
	return u
}

// ClearRevenuecatStore clears the value of the "revenuecat_store" field.
func (u *SubscriptionUpsert) ClearRevenuecatStore() *SubscriptionUpsert {
	u.SetNull(subscription.FieldRevenuecatStore)
	return u
}

// SetRevenuecatEntitlementID sets the "revenuecat_entitlement_id" field.
func (u *SubscriptionUpsert) SetRevenuecatEntitlementID(v string) *SubscriptionUpsert {
	u.Set(subscription.FieldRevenuecatEntitlementID, v)
	return u
}

// UpdateRevenuecatEntitlementID sets the "revenuecat_entitlement_id" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateRevenuecatEntitlementID() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldRevenuecatEntitlementID)
	return u
}

// ClearRevenuecatEntitlementID clears the value of the "revenuecat_entitlement_id" field.
func (u *SubscriptionUpsert) ClearRevenuecatEntitlementID() *SubscriptionUpsert {
	u.SetNull(subscription.FieldRevenuecatEntitlementID)
	return u
}

// SetRevenuecatOriginalTransactionID sets the "revenuecat_original_transaction_id" field.
func (u *SubscriptionUpsert) SetRevenuecatOriginalTransactionID(v string) *SubscriptionUpsert {
	u.Set(subscription.FieldRevenuecatOriginalTransactionID, v)
	return u
}

// UpdateRevenuecatOriginalTransactionID sets the "revenuecat_original_transaction_id" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateRevenuecatOriginalTransactionID() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldRevenuecatOriginalTransactionID)
	return u
}

// ClearRevenuecatOriginalTransactionID clears the value of the "revenuecat_original_transaction_id" field.
func (u *SubscriptionUpsert) ClearRevenuecatOriginalTransactionID() *SubscriptionUpsert {
	u.SetNull(subscription.FieldRevenuecatOriginalTransactionID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Subscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(subscription.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SubscriptionUpsertOne) UpdateNewValues() *SubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(subscription.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscription.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Subscription.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionUpsertOne) Ignore() *SubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionUpsertOne) DoNothing() *SubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionCreate.OnConflict
// documentation for more info.
func (u *SubscriptionUpsertOne) Update(set func(*SubscriptionUpsert)) *SubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionUpsertOne) SetUpdatedAt(v time.Time) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateUpdatedAt() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionUpsertOne) SetUserID(v uuid.UUID) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateUserID() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateUserID()
	})
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (u *SubscriptionUpsertOne) SetStripeCustomerID(v string) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetStripeCustomerID(v)
	})
}

// UpdateStripeCustomerID sets the "stripe_customer_id" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateStripeCustomerID() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateStripeCustomerID()
	})
}

// ClearStripeCustomerID clears the value of the "stripe_customer_id" field.
func (u *SubscriptionUpsertOne) ClearStripeCustomerID() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.ClearStripeCustomerID()
	})
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (u *SubscriptionUpsertOne) SetStripeSubscriptionID(v string) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetStripeSubscriptionID(v)
	})
}

// UpdateStripeSubscriptionID sets the "stripe_subscription_id" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateStripeSubscriptionID() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateStripeSubscriptionID()
	})
}

// ClearStripeSubscriptionID clears the value of the "stripe_subscription_id" field.
func (u *SubscriptionUpsertOne) ClearStripeSubscriptionID() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.ClearStripeSubscriptionID()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionUpsertOne) SetStatus(v primitive.SubscriptionStatus) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateStatus() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (u *SubscriptionUpsertOne) SetCurrentPeriodEnd(v time.Time) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetCurrentPeriodEnd(v)
	})
}

// UpdateCurrentPeriodEnd sets the "current_period_end" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateCurrentPeriodEnd() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateCurrentPeriodEnd()
	})
}

// ClearCurrentPeriodEnd clears the value of the "current_period_end" field.
func (u *SubscriptionUpsertOne) ClearCurrentPeriodEnd() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.ClearCurrentPeriodEnd()
	})
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (u *SubscriptionUpsertOne) SetCancelAtPeriodEnd(v bool) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetCancelAtPeriodEnd(v)
	})
}

// UpdateCancelAtPeriodEnd sets the "cancel_at_period_end" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateCancelAtPeriodEnd() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateCancelAtPeriodEnd()
	})
}

// SetRevenuecatActive sets the "revenuecat_active" field.
func (u *SubscriptionUpsertOne) SetRevenuecatActive(v bool) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetRevenuecatActive(v)
	})
}

// UpdateRevenuecatActive sets the "revenuecat_active" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateRevenuecatActive() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateRevenuecatActive()
	})
}

// SetRevenuecatExpiresAt sets the "revenuecat_expires_at" field.
func (u *SubscriptionUpsertOne) SetRevenuecatExpiresAt(v time.Time) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetRevenuecatExpiresAt(v)
	})
}

// UpdateRevenuecatExpiresAt sets the "revenuecat_expires_at" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateRevenuecatExpiresAt() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateRevenuecatExpiresAt()
	})
}

// ClearRevenuecatExpiresAt clears the value of the "revenuecat_expires_at" field.
func (u *SubscriptionUpsertOne) ClearRevenuecatExpiresAt() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.ClearRevenuecatExpiresAt()
	})
}

// SetRevenuecatStore sets the "revenuecat_store" field.
func (u *SubscriptionUpsertOne) SetRevenuecatStore(v string) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetRevenuecatStore(v)
	})
}

// UpdateRevenuecatStore sets the "revenuecat_store" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateRevenuecatStore() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateRevenuecatStore()
	})
}

// ClearRevenuecatStore clears the value of the "revenuecat_store" field.
func (u *SubscriptionUpsertOne) ClearRevenuecatStore() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.ClearRevenuecatStore()
	})
}

// SetRevenuecatEntitlementID sets the "revenuecat_entitlement_id" field.
func (u *SubscriptionUpsertOne) SetRevenuecatEntitlementID(v string) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetRevenuecatEntitlementID(v)
	})
}

// UpdateRevenuecatEntitlementID sets the "revenuecat_entitlement_id" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateRevenuecatEntitlementID() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateRevenuecatEntitlementID()
	})
}

// ClearRevenuecatEntitlementID clears the value of the "revenuecat_entitlement_id" field.
func (u *SubscriptionUpsertOne) ClearRevenuecatEntitlementID() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.ClearRevenuecatEntitlementID()
	})
}

// SetRevenuecatOriginalTransactionID sets the "revenuecat_original_transaction_id" field.
func (u *SubscriptionUpsertOne) SetRevenuecatOriginalTransactionID(v string) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetRevenuecatOriginalTransactionID(v)
	})
}

// UpdateRevenuecatOriginalTransactionID sets the "revenuecat_original_transaction_id" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateRevenuecatOriginalTransactionID() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateRevenuecatOriginalTransactionID()
	})
}

// ClearRevenuecatOriginalTransactionID clears the value of the "revenuecat_original_transaction_id" field.
func (u *SubscriptionUpsertOne) ClearRevenuecatOriginalTransactionID() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.ClearRevenuecatOriginalTransactionID()
	})
}

// Exec executes the query.
func (u *SubscriptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SubscriptionUpsertOne.ID is not supported by MySQL driver. Use SubscriptionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionCreateBulk is the builder for creating many Subscription entities in bulk.
type SubscriptionCreateBulk struct {
	config
	err      error
	builders []*SubscriptionCreate
	conflict []sql.ConflictOption
}

// Save creates the Subscription entities in the database.
func (_c *SubscriptionCreateBulk) Save(ctx context.Context) ([]*Subscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Subscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionCreateBulk) SaveX(ctx context.Context) []*Subscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Subscription.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionUpsertBulk {
	_c.conflict = opts
	return &SubscriptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Subscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionCreateBulk) OnConflictColumns(columns ...string) *SubscriptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionUpsertBulk{
		create: _c,
	}
}

// SubscriptionUpsertBulk is the builder for "upsert"-ing
// a bulk of Subscription nodes.
type SubscriptionUpsertBulk struct {
	create *SubscriptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Subscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(subscription.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SubscriptionUpsertBulk) UpdateNewValues() *SubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(subscription.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscription.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Subscription.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionUpsertBulk) Ignore() *SubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionUpsertBulk) DoNothing() *SubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionUpsertBulk) Update(set func(*SubscriptionUpsert)) *SubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionUpsertBulk) SetUpdatedAt(v time.Time) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateUpdatedAt() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionUpsertBulk) SetUserID(v uuid.UUID) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateUserID() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateUserID()
	})
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (u *SubscriptionUpsertBulk) SetStripeCustomerID(v string) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetStripeCustomerID(v)
	})
}

// UpdateStripeCustomerID sets the "stripe_customer_id" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateStripeCustomerID() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateStripeCustomerID()
	})
}

// ClearStripeCustomerID clears the value of the "stripe_customer_id" field.
func (u *SubscriptionUpsertBulk) ClearStripeCustomerID() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.ClearStripeCustomerID()
	})
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (u *SubscriptionUpsertBulk) SetStripeSubscriptionID(v string) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetStripeSubscriptionID(v)
	})
}

// UpdateStripeSubscriptionID sets the "stripe_subscription_id" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateStripeSubscriptionID() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateStripeSubscriptionID()
	})
}

// ClearStripeSubscriptionID clears the value of the "stripe_subscription_id" field.
func (u *SubscriptionUpsertBulk) ClearStripeSubscriptionID() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.ClearStripeSubscriptionID()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionUpsertBulk) SetStatus(v primitive.SubscriptionStatus) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateStatus() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (u *SubscriptionUpsertBulk) SetCurrentPeriodEnd(v time.Time) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetCurrentPeriodEnd(v)
	})
}

// UpdateCurrentPeriodEnd sets the "current_period_end" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateCurrentPeriodEnd() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateCurrentPeriodEnd()
	})
}

// ClearCurrentPeriodEnd clears the value of the "current_period_end" field.
func (u *SubscriptionUpsertBulk) ClearCurrentPeriodEnd() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.ClearCurrentPeriodEnd()
	})
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (u *SubscriptionUpsertBulk) SetCancelAtPeriodEnd(v bool) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetCancelAtPeriodEnd(v)
	})
}

// UpdateCancelAtPeriodEnd sets the "cancel_at_period_end" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateCancelAtPeriodEnd() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateCancelAtPeriodEnd()
	})
}

// SetRevenuecatActive sets the "revenuecat_active" field.
func (u *SubscriptionUpsertBulk) SetRevenuecatActive(v bool) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetRevenuecatActive(v)
	})
}

// UpdateRevenuecatActive sets the "revenuecat_active" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateRevenuecatActive() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateRevenuecatActive()
	})
}

// SetRevenuecatExpiresAt sets the "revenuecat_expires_at" field.
func (u *SubscriptionUpsertBulk) SetRevenuecatExpiresAt(v time.Time) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetRevenuecatExpiresAt(v)
	})
}

// UpdateRevenuecatExpiresAt sets the "revenuecat_expires_at" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateRevenuecatExpiresAt() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateRevenuecatExpiresAt()
	})
}

// ClearRevenuecatExpiresAt clears the value of the "revenuecat_expires_at" field.
func (u *SubscriptionUpsertBulk) ClearRevenuecatExpiresAt() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.ClearRevenuecatExpiresAt()
	})
}

// SetRevenuecatStore sets the "revenuecat_store" field.
func (u *SubscriptionUpsertBulk) SetRevenuecatStore(v string) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetRevenuecatStore(v)
	})
}

// UpdateRevenuecatStore sets the "revenuecat_store" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateRevenuecatStore() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateRevenuecatStore()
	})
}

// ClearRevenuecatStore clears the value of the "revenuecat_store" field.
func (u *SubscriptionUpsertBulk) ClearRevenuecatStore() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.ClearRevenuecatStore()
	})
}

// SetRevenuecatEntitlementID sets the "revenuecat_entitlement_id" field.
func (u *SubscriptionUpsertBulk) SetRevenuecatEntitlementID(v string) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetRevenuecatEntitlementID(v)
	})
}

// UpdateRevenuecatEntitlementID sets the "revenuecat_entitlement_id" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateRevenuecatEntitlementID() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateRevenuecatEntitlementID()
	})
}

// ClearRevenuecatEntitlementID clears the value of the "revenuecat_entitlement_id" field.
func (u *SubscriptionUpsertBulk) ClearRevenuecatEntitlementID() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.ClearRevenuecatEntitlementID()
	})
}

// SetRevenuecatOriginalTransactionID sets the "revenuecat_original_transaction_id" field.
func (u *SubscriptionUpsertBulk) SetRevenuecatOriginalTransactionID(v string) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetRevenuecatOriginalTransactionID(v)
	})
}

// UpdateRevenuecatOriginalTransactionID sets the "revenuecat_original_transaction_id" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateRevenuecatOriginalTransactionID() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateRevenuecatOriginalTransactionID()
	})
}

// ClearRevenuecatOriginalTransactionID clears the value of the "revenuecat_original_transaction_id" field.
func (u *SubscriptionUpsertBulk) ClearRevenuecatOriginalTransactionID() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.ClearRevenuecatOriginalTransactionID()
	})
}

// Exec executes the query.
func (u *SubscriptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
