// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BooksColumns holds the columns for the "books" table.
	BooksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "key", Type: field.TypeString, Unique: true, Size: 20},
		{Name: "title", Type: field.TypeString, Size: 100},
		{Name: "author_names", Type: field.TypeJSON, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "cover_url", Type: field.TypeString, Nullable: true, Size: 1000},
		{Name: "uploaded", Type: field.TypeBool, Default: false},
		{Name: "parsed", Type: field.TypeBool, Default: false},
		{Name: "prepared", Type: field.TypeBool, Default: false},
		{Name: "script_generated", Type: field.TypeBool, Default: false},
		{Name: "tts_generated", Type: field.TypeBool, Default: false},
		{Name: "language", Type: field.TypeEnum, Enums: []string{"fr", "en"}, Default: "fr"},
		{Name: "genre", Type: field.TypeEnum, Enums: []string{"fiction", "none-fiction"}, Default: "none-fiction"},
		{Name: "failed", Type: field.TypeBool, Default: false},
		{Name: "failed_stage", Type: field.TypeString, Nullable: true, Size: 20},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "retry_disabled", Type: field.TypeBool, Default: false},
		{Name: "token_usage", Type: field.TypeJSON, Nullable: true},
	}
	// BooksTable holds the schema information for the "books" table.
	BooksTable = &schema.Table{
		Name:       "books",
		Columns:    BooksColumns,
		PrimaryKey: []*schema.Column{BooksColumns[0]},
	}
	// SubscriptionsColumns holds the columns for the "subscriptions" table.
	SubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID, Unique: true},
		{Name: "stripe_customer_id", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "stripe_subscription_id", Type: field.TypeString, Unique: true, Nullable: true, Size: 50},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"incomplete", "incomplete_expired", "trialing", "active", "past_due", "canceled", "unpaid", "paused"}, Default: "incomplete"},
		{Name: "current_period_end", Type: field.TypeTime, Nullable: true},
		{Name: "cancel_at_period_end", Type: field.TypeBool, Default: false},
	}
	// SubscriptionsTable holds the schema information for the "subscriptions" table.
	SubscriptionsTable = &schema.Table{
		Name:       "subscriptions",
		Columns:    SubscriptionsColumns,
		PrimaryKey: []*schema.Column{SubscriptionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "subscription_status",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionsColumns[6]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "firstname", Type: field.TypeString, Size: 100},
		{Name: "lastname", Type: field.TypeString, Size: 100},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 200},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"basic"}, Default: "basic"},
		{Name: "language", Type: field.TypeEnum, Enums: []string{"fr", "en"}, Default: "fr"},
		{Name: "password_hash", Type: field.TypeBytes},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BooksTable,
		SubscriptionsTable,
		UsersTable,
	}
)

func init() {
}
