// Code generated by ent, DO NOT EDIT.

package book

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the book type in the database.
	Label = "book"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldAuthorNames holds the string denoting the author_names field in the database.
	FieldAuthorNames = "author_names"
	// FieldAuthorKeys holds the string denoting the author_keys field in the database.
	FieldAuthorKeys = "author_keys"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCoverURL holds the string denoting the cover_url field in the database.
	FieldCoverURL = "cover_url"
	// FieldUploaded holds the string denoting the uploaded field in the database.
	FieldUploaded = "uploaded"
	// FieldParsed holds the string denoting the parsed field in the database.
	FieldParsed = "parsed"
	// FieldPrepared holds the string denoting the prepared field in the database.
	FieldPrepared = "prepared"
	// FieldScriptGenerated holds the string denoting the script_generated field in the database.
	FieldScriptGenerated = "script_generated"
	// FieldTtsGenerated holds the string denoting the tts_generated field in the database.
	FieldTtsGenerated = "tts_generated"
	// Table holds the table name of the book in the database.
	Table = "books"
)

// Columns holds all SQL columns for book fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldKey,
	FieldTitle,
	FieldAuthorNames,
	FieldAuthorKeys,
	FieldDescription,
	FieldCoverURL,
	FieldUploaded,
	FieldParsed,
	FieldPrepared,
	FieldScriptGenerated,
	FieldTtsGenerated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// KeyValidator is a validator for the "key" field. It is called by the builders before save.
	KeyValidator func(string) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// CoverURLValidator is a validator for the "cover_url" field. It is called by the builders before save.
	CoverURLValidator func(string) error
	// DefaultUploaded holds the default value on creation for the "uploaded" field.
	DefaultUploaded bool
	// DefaultParsed holds the default value on creation for the "parsed" field.
	DefaultParsed bool
	// DefaultPrepared holds the default value on creation for the "prepared" field.
	DefaultPrepared bool
	// DefaultScriptGenerated holds the default value on creation for the "script_generated" field.
	DefaultScriptGenerated bool
	// DefaultTtsGenerated holds the default value on creation for the "tts_generated" field.
	DefaultTtsGenerated bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Book queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCoverURL orders the results by the cover_url field.
func ByCoverURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoverURL, opts...).ToFunc()
}

// ByUploaded orders the results by the uploaded field.
func ByUploaded(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploaded, opts...).ToFunc()
}

// ByParsed orders the results by the parsed field.
func ByParsed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParsed, opts...).ToFunc()
}

// ByPrepared orders the results by the prepared field.
func ByPrepared(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrepared, opts...).ToFunc()
}

// ByScriptGenerated orders the results by the script_generated field.
func ByScriptGenerated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScriptGenerated, opts...).ToFunc()
}

// ByTtsGenerated orders the results by the tts_generated field.
func ByTtsGenerated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTtsGenerated, opts...).ToFunc()
}
