// Code generated by ent, DO NOT EDIT.

package subscription

import (
	"fmt"
	"hkorpo/book/internal/primitive"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the subscription type in the database.
	Label = "subscription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldStripeCustomerID holds the string denoting the stripe_customer_id field in the database.
	FieldStripeCustomerID = "stripe_customer_id"
	// FieldStripeSubscriptionID holds the string denoting the stripe_subscription_id field in the database.
	FieldStripeSubscriptionID = "stripe_subscription_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCurrentPeriodEnd holds the string denoting the current_period_end field in the database.
	FieldCurrentPeriodEnd = "current_period_end"
	// FieldCancelAtPeriodEnd holds the string denoting the cancel_at_period_end field in the database.
	FieldCancelAtPeriodEnd = "cancel_at_period_end"
	// FieldRevenuecatActive holds the string denoting the revenuecat_active field in the database.
	FieldRevenuecatActive = "revenuecat_active"
	// FieldRevenuecatExpiresAt holds the string denoting the revenuecat_expires_at field in the database.
	FieldRevenuecatExpiresAt = "revenuecat_expires_at"
	// FieldRevenuecatStore holds the string denoting the revenuecat_store field in the database.
	FieldRevenuecatStore = "revenuecat_store"
	// FieldRevenuecatEntitlementID holds the string denoting the revenuecat_entitlement_id field in the database.
	FieldRevenuecatEntitlementID = "revenuecat_entitlement_id"
	// FieldRevenuecatOriginalTransactionID holds the string denoting the revenuecat_original_transaction_id field in the database.
	FieldRevenuecatOriginalTransactionID = "revenuecat_original_transaction_id"
	// Table holds the table name of the subscription in the database.
	Table = "subscriptions"
)

// Columns holds all SQL columns for subscription fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldStripeCustomerID,
	FieldStripeSubscriptionID,
	FieldStatus,
	FieldCurrentPeriodEnd,
	FieldCancelAtPeriodEnd,
	FieldRevenuecatActive,
	FieldRevenuecatExpiresAt,
	FieldRevenuecatStore,
	FieldRevenuecatEntitlementID,
	FieldRevenuecatOriginalTransactionID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// StripeCustomerIDValidator is a validator for the "stripe_customer_id" field. It is called by the builders before save.
	StripeCustomerIDValidator func(string) error
	// StripeSubscriptionIDValidator is a validator for the "stripe_subscription_id" field. It is called by the builders before save.
	StripeSubscriptionIDValidator func(string) error
	// DefaultCancelAtPeriodEnd holds the default value on creation for the "cancel_at_period_end" field.
	DefaultCancelAtPeriodEnd bool
	// DefaultRevenuecatActive holds the default value on creation for the "revenuecat_active" field.
	DefaultRevenuecatActive bool
	// RevenuecatStoreValidator is a validator for the "revenuecat_store" field. It is called by the builders before save.
	RevenuecatStoreValidator func(string) error
	// RevenuecatEntitlementIDValidator is a validator for the "revenuecat_entitlement_id" field. It is called by the builders before save.
	RevenuecatEntitlementIDValidator func(string) error
	// RevenuecatOriginalTransactionIDValidator is a validator for the "revenuecat_original_transaction_id" field. It is called by the builders before save.
	RevenuecatOriginalTransactionIDValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

const DefaultStatus primitive.SubscriptionStatus = "incomplete"

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s primitive.SubscriptionStatus) error {
	switch s.String() {
	case "incomplete", "incomplete_expired", "trialing", "active", "past_due", "canceled", "unpaid", "paused":
		return nil
	default:
		return fmt.Errorf("subscription: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Subscription queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByStripeCustomerID orders the results by the stripe_customer_id field.
func ByStripeCustomerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripeCustomerID, opts...).ToFunc()
}

// ByStripeSubscriptionID orders the results by the stripe_subscription_id field.
func ByStripeSubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStripeSubscriptionID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCurrentPeriodEnd orders the results by the current_period_end field.
func ByCurrentPeriodEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentPeriodEnd, opts...).ToFunc()
}

// ByCancelAtPeriodEnd orders the results by the cancel_at_period_end field.
func ByCancelAtPeriodEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelAtPeriodEnd, opts...).ToFunc()
}

// ByRevenuecatActive orders the results by the revenuecat_active field.
func ByRevenuecatActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevenuecatActive, opts...).ToFunc()
}

// ByRevenuecatExpiresAt orders the results by the revenuecat_expires_at field.
func ByRevenuecatExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevenuecatExpiresAt, opts...).ToFunc()
}

// ByRevenuecatStore orders the results by the revenuecat_store field.
func ByRevenuecatStore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevenuecatStore, opts...).ToFunc()
}

// ByRevenuecatEntitlementID orders the results by the revenuecat_entitlement_id field.
func ByRevenuecatEntitlementID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevenuecatEntitlementID, opts...).ToFunc()
}

// ByRevenuecatOriginalTransactionID orders the results by the revenuecat_original_transaction_id field.
func ByRevenuecatOriginalTransactionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevenuecatOriginalTransactionID, opts...).ToFunc()
}
