// Code generated by ent, DO NOT EDIT.

package subscription

import (
	"hkorpo/book/internal/primitive"
	"hkorpo/book/pkg/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldUserID, v))
}

// StripeCustomerID applies equality check predicate on the "stripe_customer_id" field. It's identical to StripeCustomerIDEQ.
func StripeCustomerID(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldStripeCustomerID, v))
}

// StripeSubscriptionID applies equality check predicate on the "stripe_subscription_id" field. It's identical to StripeSubscriptionIDEQ.
func StripeSubscriptionID(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldStripeSubscriptionID, v))
}

// CurrentPeriodEnd applies equality check predicate on the "current_period_end" field. It's identical to CurrentPeriodEndEQ.
func CurrentPeriodEnd(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCurrentPeriodEnd, v))
}

// CancelAtPeriodEnd applies equality check predicate on the "cancel_at_period_end" field. It's identical to CancelAtPeriodEndEQ.
func CancelAtPeriodEnd(v bool) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCancelAtPeriodEnd, v))
}

// RevenuecatActive applies equality check predicate on the "revenuecat_active" field. It's identical to RevenuecatActiveEQ.
func RevenuecatActive(v bool) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRevenuecatActive, v))
}

// RevenuecatExpiresAt applies equality check predicate on the "revenuecat_expires_at" field. It's identical to RevenuecatExpiresAtEQ.
func RevenuecatExpiresAt(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRevenuecatExpiresAt, v))
}

// RevenuecatStore applies equality check predicate on the "revenuecat_store" field. It's identical to RevenuecatStoreEQ.
func RevenuecatStore(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRevenuecatStore, v))
}

// RevenuecatEntitlementID applies equality check predicate on the "revenuecat_entitlement_id" field. It's identical to RevenuecatEntitlementIDEQ.
func RevenuecatEntitlementID(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRevenuecatEntitlementID, v))
}

// RevenuecatOriginalTransactionID applies equality check predicate on the "revenuecat_original_transaction_id" field. It's identical to RevenuecatOriginalTransactionIDEQ.
func RevenuecatOriginalTransactionID(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRevenuecatOriginalTransactionID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldUserID, v))
}

// StripeCustomerIDEQ applies the EQ predicate on the "stripe_customer_id" field.
func StripeCustomerIDEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldStripeCustomerID, v))
}

// StripeCustomerIDNEQ applies the NEQ predicate on the "stripe_customer_id" field.
func StripeCustomerIDNEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldStripeCustomerID, v))
}

// StripeCustomerIDIn applies the In predicate on the "stripe_customer_id" field.
func StripeCustomerIDIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldStripeCustomerID, vs...))
}

// StripeCustomerIDNotIn applies the NotIn predicate on the "stripe_customer_id" field.
func StripeCustomerIDNotIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldStripeCustomerID, vs...))
}

// StripeCustomerIDGT applies the GT predicate on the "stripe_customer_id" field.
func StripeCustomerIDGT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldStripeCustomerID, v))
}

// StripeCustomerIDGTE applies the GTE predicate on the "stripe_customer_id" field.
func StripeCustomerIDGTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldStripeCustomerID, v))
}

// StripeCustomerIDLT applies the LT predicate on the "stripe_customer_id" field.
func StripeCustomerIDLT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldStripeCustomerID, v))
}

// StripeCustomerIDLTE applies the LTE predicate on the "stripe_customer_id" field.
func StripeCustomerIDLTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldStripeCustomerID, v))
}

// StripeCustomerIDContains applies the Contains predicate on the "stripe_customer_id" field.
func StripeCustomerIDContains(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContains(FieldStripeCustomerID, v))
}

// StripeCustomerIDHasPrefix applies the HasPrefix predicate on the "stripe_customer_id" field.
func StripeCustomerIDHasPrefix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasPrefix(FieldStripeCustomerID, v))
}

// StripeCustomerIDHasSuffix applies the HasSuffix predicate on the "stripe_customer_id" field.
func StripeCustomerIDHasSuffix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasSuffix(FieldStripeCustomerID, v))
}

// StripeCustomerIDIsNil applies the IsNil predicate on the "stripe_customer_id" field.
func StripeCustomerIDIsNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldIsNull(FieldStripeCustomerID))
}

// StripeCustomerIDNotNil applies the NotNil predicate on the "stripe_customer_id" field.
func StripeCustomerIDNotNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldNotNull(FieldStripeCustomerID))
}

// StripeCustomerIDEqualFold applies the EqualFold predicate on the "stripe_customer_id" field.
func StripeCustomerIDEqualFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEqualFold(FieldStripeCustomerID, v))
}

// StripeCustomerIDContainsFold applies the ContainsFold predicate on the "stripe_customer_id" field.
func StripeCustomerIDContainsFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContainsFold(FieldStripeCustomerID, v))
}

// StripeSubscriptionIDEQ applies the EQ predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDNEQ applies the NEQ predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDNEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDIn applies the In predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldStripeSubscriptionID, vs...))
}

// StripeSubscriptionIDNotIn applies the NotIn predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDNotIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldStripeSubscriptionID, vs...))
}

// StripeSubscriptionIDGT applies the GT predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDGT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDGTE applies the GTE predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDGTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDLT applies the LT predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDLT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDLTE applies the LTE predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDLTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDContains applies the Contains predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDContains(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContains(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDHasPrefix applies the HasPrefix predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDHasPrefix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasPrefix(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDHasSuffix applies the HasSuffix predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDHasSuffix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasSuffix(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDIsNil applies the IsNil predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDIsNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldIsNull(FieldStripeSubscriptionID))
}

// StripeSubscriptionIDNotNil applies the NotNil predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDNotNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldNotNull(FieldStripeSubscriptionID))
}

// StripeSubscriptionIDEqualFold applies the EqualFold predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDEqualFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEqualFold(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDContainsFold applies the ContainsFold predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDContainsFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContainsFold(FieldStripeSubscriptionID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v primitive.SubscriptionStatus) predicate.Subscription {
	vc := v
	return predicate.Subscription(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v primitive.SubscriptionStatus) predicate.Subscription {
	vc := v
	return predicate.Subscription(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...primitive.SubscriptionStatus) predicate.Subscription {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Subscription(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...primitive.SubscriptionStatus) predicate.Subscription {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Subscription(sql.FieldNotIn(FieldStatus, v...))
}

// CurrentPeriodEndEQ applies the EQ predicate on the "current_period_end" field.
func CurrentPeriodEndEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCurrentPeriodEnd, v))
}

// CurrentPeriodEndNEQ applies the NEQ predicate on the "current_period_end" field.
func CurrentPeriodEndNEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldCurrentPeriodEnd, v))
}

// CurrentPeriodEndIn applies the In predicate on the "current_period_end" field.
func CurrentPeriodEndIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldCurrentPeriodEnd, vs...))
}

// CurrentPeriodEndNotIn applies the NotIn predicate on the "current_period_end" field.
func CurrentPeriodEndNotIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldCurrentPeriodEnd, vs...))
}

// CurrentPeriodEndGT applies the GT predicate on the "current_period_end" field.
func CurrentPeriodEndGT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldCurrentPeriodEnd, v))
}

// CurrentPeriodEndGTE applies the GTE predicate on the "current_period_end" field.
func CurrentPeriodEndGTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldCurrentPeriodEnd, v))
}

// CurrentPeriodEndLT applies the LT predicate on the "current_period_end" field.
func CurrentPeriodEndLT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldCurrentPeriodEnd, v))
}

// CurrentPeriodEndLTE applies the LTE predicate on the "current_period_end" field.
func CurrentPeriodEndLTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldCurrentPeriodEnd, v))
}

// CurrentPeriodEndIsNil applies the IsNil predicate on the "current_period_end" field.
func CurrentPeriodEndIsNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldIsNull(FieldCurrentPeriodEnd))
}

// CurrentPeriodEndNotNil applies the NotNil predicate on the "current_period_end" field.
func CurrentPeriodEndNotNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldNotNull(FieldCurrentPeriodEnd))
}

// CancelAtPeriodEndEQ applies the EQ predicate on the "cancel_at_period_end" field.
func CancelAtPeriodEndEQ(v bool) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCancelAtPeriodEnd, v))
}

// CancelAtPeriodEndNEQ applies the NEQ predicate on the "cancel_at_period_end" field.
func CancelAtPeriodEndNEQ(v bool) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldCancelAtPeriodEnd, v))
}

// RevenuecatActiveEQ applies the EQ predicate on the "revenuecat_active" field.
func RevenuecatActiveEQ(v bool) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRevenuecatActive, v))
}

// RevenuecatActiveNEQ applies the NEQ predicate on the "revenuecat_active" field.
func RevenuecatActiveNEQ(v bool) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldRevenuecatActive, v))
}

// RevenuecatExpiresAtEQ applies the EQ predicate on the "revenuecat_expires_at" field.
func RevenuecatExpiresAtEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRevenuecatExpiresAt, v))
}

// RevenuecatExpiresAtNEQ applies the NEQ predicate on the "revenuecat_expires_at" field.
func RevenuecatExpiresAtNEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldRevenuecatExpiresAt, v))
}

// RevenuecatExpiresAtIn applies the In predicate on the "revenuecat_expires_at" field.
func RevenuecatExpiresAtIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldRevenuecatExpiresAt, vs...))
}

// RevenuecatExpiresAtNotIn applies the NotIn predicate on the "revenuecat_expires_at" field.
func RevenuecatExpiresAtNotIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldRevenuecatExpiresAt, vs...))
}

// RevenuecatExpiresAtGT applies the GT predicate on the "revenuecat_expires_at" field.
func RevenuecatExpiresAtGT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldRevenuecatExpiresAt, v))
}

// RevenuecatExpiresAtGTE applies the GTE predicate on the "revenuecat_expires_at" field.
func RevenuecatExpiresAtGTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldRevenuecatExpiresAt, v))
}

// RevenuecatExpiresAtLT applies the LT predicate on the "revenuecat_expires_at" field.
func RevenuecatExpiresAtLT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldRevenuecatExpiresAt, v))
}

// RevenuecatExpiresAtLTE applies the LTE predicate on the "revenuecat_expires_at" field.
func RevenuecatExpiresAtLTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldRevenuecatExpiresAt, v))
}

// RevenuecatExpiresAtIsNil applies the IsNil predicate on the "revenuecat_expires_at" field.
func RevenuecatExpiresAtIsNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldIsNull(FieldRevenuecatExpiresAt))
}

// RevenuecatExpiresAtNotNil applies the NotNil predicate on the "revenuecat_expires_at" field.
func RevenuecatExpiresAtNotNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldNotNull(FieldRevenuecatExpiresAt))
}

// RevenuecatStoreEQ applies the EQ predicate on the "revenuecat_store" field.
func RevenuecatStoreEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRevenuecatStore, v))
}

// RevenuecatStoreNEQ applies the NEQ predicate on the "revenuecat_store" field.
func RevenuecatStoreNEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldRevenuecatStore, v))
}

// RevenuecatStoreIn applies the In predicate on the "revenuecat_store" field.
func RevenuecatStoreIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldRevenuecatStore, vs...))
}

// RevenuecatStoreNotIn applies the NotIn predicate on the "revenuecat_store" field.
func RevenuecatStoreNotIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldRevenuecatStore, vs...))
}

// RevenuecatStoreGT applies the GT predicate on the "revenuecat_store" field.
func RevenuecatStoreGT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldRevenuecatStore, v))
}

// RevenuecatStoreGTE applies the GTE predicate on the "revenuecat_store" field.
func RevenuecatStoreGTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldRevenuecatStore, v))
}

// RevenuecatStoreLT applies the LT predicate on the "revenuecat_store" field.
func RevenuecatStoreLT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldRevenuecatStore, v))
}

// RevenuecatStoreLTE applies the LTE predicate on the "revenuecat_store" field.
func RevenuecatStoreLTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldRevenuecatStore, v))
}

// RevenuecatStoreContains applies the Contains predicate on the "revenuecat_store" field.
func RevenuecatStoreContains(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContains(FieldRevenuecatStore, v))
}

// RevenuecatStoreHasPrefix applies the HasPrefix predicate on the "revenuecat_store" field.
func RevenuecatStoreHasPrefix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasPrefix(FieldRevenuecatStore, v))
}

// RevenuecatStoreHasSuffix applies the HasSuffix predicate on the "revenuecat_store" field.
func RevenuecatStoreHasSuffix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasSuffix(FieldRevenuecatStore, v))
}

// RevenuecatStoreIsNil applies the IsNil predicate on the "revenuecat_store" field.
func RevenuecatStoreIsNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldIsNull(FieldRevenuecatStore))
}

// RevenuecatStoreNotNil applies the NotNil predicate on the "revenuecat_store" field.
func RevenuecatStoreNotNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldNotNull(FieldRevenuecatStore))
}

// RevenuecatStoreEqualFold applies the EqualFold predicate on the "revenuecat_store" field.
func RevenuecatStoreEqualFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEqualFold(FieldRevenuecatStore, v))
}

// RevenuecatStoreContainsFold applies the ContainsFold predicate on the "revenuecat_store" field.
func RevenuecatStoreContainsFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContainsFold(FieldRevenuecatStore, v))
}

// RevenuecatEntitlementIDEQ applies the EQ predicate on the "revenuecat_entitlement_id" field.
func RevenuecatEntitlementIDEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRevenuecatEntitlementID, v))
}

// RevenuecatEntitlementIDNEQ applies the NEQ predicate on the "revenuecat_entitlement_id" field.
func RevenuecatEntitlementIDNEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldRevenuecatEntitlementID, v))
}

// RevenuecatEntitlementIDIn applies the In predicate on the "revenuecat_entitlement_id" field.
func RevenuecatEntitlementIDIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldRevenuecatEntitlementID, vs...))
}

// RevenuecatEntitlementIDNotIn applies the NotIn predicate on the "revenuecat_entitlement_id" field.
func RevenuecatEntitlementIDNotIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldRevenuecatEntitlementID, vs...))
}

// RevenuecatEntitlementIDGT applies the GT predicate on the "revenuecat_entitlement_id" field.
func RevenuecatEntitlementIDGT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldRevenuecatEntitlementID, v))
}

// RevenuecatEntitlementIDGTE applies the GTE predicate on the "revenuecat_entitlement_id" field.
func RevenuecatEntitlementIDGTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldRevenuecatEntitlementID, v))
}

// RevenuecatEntitlementIDLT applies the LT predicate on the "revenuecat_entitlement_id" field.
func RevenuecatEntitlementIDLT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldRevenuecatEntitlementID, v))
}

// RevenuecatEntitlementIDLTE applies the LTE predicate on the "revenuecat_entitlement_id" field.
func RevenuecatEntitlementIDLTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldRevenuecatEntitlementID, v))
}

// RevenuecatEntitlementIDContains applies the Contains predicate on the "revenuecat_entitlement_id" field.
func RevenuecatEntitlementIDContains(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContains(FieldRevenuecatEntitlementID, v))
}

// RevenuecatEntitlementIDHasPrefix applies the HasPrefix predicate on the "revenuecat_entitlement_id" field.
func RevenuecatEntitlementIDHasPrefix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasPrefix(FieldRevenuecatEntitlementID, v))
}

// RevenuecatEntitlementIDHasSuffix applies the HasSuffix predicate on the "revenuecat_entitlement_id" field.
func RevenuecatEntitlementIDHasSuffix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasSuffix(FieldRevenuecatEntitlementID, v))
}

// RevenuecatEntitlementIDIsNil applies the IsNil predicate on the "revenuecat_entitlement_id" field.
func RevenuecatEntitlementIDIsNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldIsNull(FieldRevenuecatEntitlementID))
}

// RevenuecatEntitlementIDNotNil applies the NotNil predicate on the "revenuecat_entitlement_id" field.
func RevenuecatEntitlementIDNotNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldNotNull(FieldRevenuecatEntitlementID))
}

// RevenuecatEntitlementIDEqualFold applies the EqualFold predicate on the "revenuecat_entitlement_id" field.
func RevenuecatEntitlementIDEqualFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEqualFold(FieldRevenuecatEntitlementID, v))
}

// RevenuecatEntitlementIDContainsFold applies the ContainsFold predicate on the "revenuecat_entitlement_id" field.
func RevenuecatEntitlementIDContainsFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContainsFold(FieldRevenuecatEntitlementID, v))
}

// RevenuecatOriginalTransactionIDEQ applies the EQ predicate on the "revenuecat_original_transaction_id" field.
func RevenuecatOriginalTransactionIDEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldRevenuecatOriginalTransactionID, v))
}

// RevenuecatOriginalTransactionIDNEQ applies the NEQ predicate on the "revenuecat_original_transaction_id" field.
func RevenuecatOriginalTransactionIDNEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldRevenuecatOriginalTransactionID, v))
}

// RevenuecatOriginalTransactionIDIn applies the In predicate on the "revenuecat_original_transaction_id" field.
func RevenuecatOriginalTransactionIDIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldRevenuecatOriginalTransactionID, vs...))
}

// RevenuecatOriginalTransactionIDNotIn applies the NotIn predicate on the "revenuecat_original_transaction_id" field.
func RevenuecatOriginalTransactionIDNotIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldRevenuecatOriginalTransactionID, vs...))
}

// RevenuecatOriginalTransactionIDGT applies the GT predicate on the "revenuecat_original_transaction_id" field.
func RevenuecatOriginalTransactionIDGT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldRevenuecatOriginalTransactionID, v))
}

// RevenuecatOriginalTransactionIDGTE applies the GTE predicate on the "revenuecat_original_transaction_id" field.
func RevenuecatOriginalTransactionIDGTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldRevenuecatOriginalTransactionID, v))
}

// RevenuecatOriginalTransactionIDLT applies the LT predicate on the "revenuecat_original_transaction_id" field.
func RevenuecatOriginalTransactionIDLT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldRevenuecatOriginalTransactionID, v))
}

// RevenuecatOriginalTransactionIDLTE applies the LTE predicate on the "revenuecat_original_transaction_id" field.
func RevenuecatOriginalTransactionIDLTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldRevenuecatOriginalTransactionID, v))
}

// RevenuecatOriginalTransactionIDContains applies the Contains predicate on the "revenuecat_original_transaction_id" field.
func RevenuecatOriginalTransactionIDContains(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContains(FieldRevenuecatOriginalTransactionID, v))
}

// RevenuecatOriginalTransactionIDHasPrefix applies the HasPrefix predicate on the "revenuecat_original_transaction_id" field.
func RevenuecatOriginalTransactionIDHasPrefix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasPrefix(FieldRevenuecatOriginalTransactionID, v))
}

// RevenuecatOriginalTransactionIDHasSuffix applies the HasSuffix predicate on the "revenuecat_original_transaction_id" field.
func RevenuecatOriginalTransactionIDHasSuffix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasSuffix(FieldRevenuecatOriginalTransactionID, v))
}

// RevenuecatOriginalTransactionIDIsNil applies the IsNil predicate on the "revenuecat_original_transaction_id" field.
func RevenuecatOriginalTransactionIDIsNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldIsNull(FieldRevenuecatOriginalTransactionID))
}

// RevenuecatOriginalTransactionIDNotNil applies the NotNil predicate on the "revenuecat_original_transaction_id" field.
func RevenuecatOriginalTransactionIDNotNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldNotNull(FieldRevenuecatOriginalTransactionID))
}

// RevenuecatOriginalTransactionIDEqualFold applies the EqualFold predicate on the "revenuecat_original_transaction_id" field.
func RevenuecatOriginalTransactionIDEqualFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEqualFold(FieldRevenuecatOriginalTransactionID, v))
}

// RevenuecatOriginalTransactionIDContainsFold applies the ContainsFold predicate on the "revenuecat_original_transaction_id" field.
func RevenuecatOriginalTransactionIDContainsFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContainsFold(FieldRevenuecatOriginalTransactionID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.NotPredicates(p))
}
